### ISSUE TITLE
Minecraft the main menu does not open

### ISSUE THREAD

**Issue by Valera7777** [sciguyryan/TheCrackPack#1000]
launch Yogcast.what to do?

[07/6/2015 08:00:32 AM] Console Cleared
[07/6/2015 08:00:34 AM] Logging into Minecraft!
[07/6/2015 08:00:34 AM] Trying to login with access token!
[07/6/2015 08:00:34 AM] Launching pack Yogscast Complete Pack 2.9.3.4-RR-YOGS for Minecraft 1.6.4
[07/6/2015 08:00:34 AM] Launching Minecraft with the following arguments (user related stuff has been removed): [C:\Program Files\Java\jre1.8.0_45\bin\javaw, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -XX:-OmitStackTraceInFastThrow, -XX:+UseConcMarkSweepGC, -XX:+CMSIncrementalMode, -XX:-UseAdaptiveSizePolicy, -Xms256M, -Xmx7680M, -XX:MetaspaceSize=256M, -Duser.language=en, -Duser.country=US, -Dfml.log.level=INFO, -Djava.library.path=**USERSDIR**\Instances\YogscastCompletePack\bin\natives, -cp, **USERSDIR**\ATLauncher.exe;anything;**USERSDIR**\Instances\YogscastCompletePack\jarmods\forge-1.6.4-9.11.1.965-universal.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\launchwrapper-1.8.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\asm-all-4.1.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\scala-compiler-2.10.2.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\scala-library-2.10.2.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\lzma-0.0.1.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\jopt-simple-4.5.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\liteloader-1.6.4.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\codecjorbis-20101023.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\codecwav-20101023.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\libraryjavasound-20101123.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\librarylwjglopenal-20100824.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\soundsystem-20120107.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\argo-2.25_fixed.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\bcprov-jdk15on-1.47.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\guava-14.0.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\commons-lang3-3.1.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\commons-io-2.4.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\jinput-2.0.5.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\jutils-1.0.0.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\gson-2.2.2.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\lwjgl-2.9.0.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\lwjgl_util-2.9.0.jar;**USERSDIR**\Instances\YogscastCompletePack\bin\minecraft.jar, net.minecraft.launchwrapper.Launch, --username, REDACTED, --session, token:REDACTED:572c7a5650fb46a4a81d5747cb2ec534, --version, 1.6.4, --gameDir, **USERSDIR**\Instances\YogscastCompletePack, --assetsDir, **USERSDIR**\Configs\Resources\virtual\legacy, --width=1280, --height=720, --tweakClass=cpw.mods.fml.common.launcher.FMLTweaker, --tweakClass, com.mumfrey.liteloader.launch.LiteLoaderTweaker]
[07/6/2015 08:00:35 AM] Jun 07, 2015 8:00:35 AM net.minecraft.launchwrapper.LogWrapper log
[07/6/2015 08:00:35 AM] INFO: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[07/6/2015 08:00:35 AM] Jun 07, 2015 8:00:35 AM net.minecraft.launchwrapper.LogWrapper log
[07/6/2015 08:00:35 AM] INFO: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[07/6/2015 08:00:35 AM] Jun 07, 2015 8:00:35 AM net.minecraft.launchwrapper.LogWrapper log
[07/6/2015 08:00:35 AM] INFO: Loading tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[07/6/2015 08:00:35 AM] Jun 07, 2015 8:00:35 AM net.minecraft.launchwrapper.LogWrapper log
[07/6/2015 08:00:35 AM] INFO: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[07/6/2015 08:00:35 AM] [INFO] [ForgeModLoader] Forge Mod Loader version 6.4.49.965 for Minecraft 1.6.4 loading
[07/6/2015 08:00:35 AM] [INFO] [ForgeModLoader] Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_45, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_45
[07/6/2015 08:00:35 AM] [WARNING] [ForgeModLoader] The coremod universalelectricity.core.UELoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:35 AM] [WARNING] [ForgeModLoader] The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:35 AM] [INFO] [STDERR] Warning: version of ForgeMultipart-universal-1.6.4-, 1.0.1.268 is newer than request 1.0.0.244
[07/6/2015 08:00:35 AM] [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:35 AM] [WARNING] [ForgeModLoader] The coremod worldcore.asm.WCFMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:35 AM] [WARNING] [ForgeModLoader] The coremod am2.preloader.AM2PreloaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:35 AM] [INFO] [ForgeModLoader] AMCore initializing...stand back!  I'm going to try MAGIC!
[07/6/2015 08:00:35 AM] [WARNING] [ForgeModLoader] The coremod appeng.transformer.AppEngCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:35 AM] [INFO] [ForgeModLoader] [AppEng] Core Init
[07/6/2015 08:00:35 AM] [WARNING] [ForgeModLoader] The coremod biomesoplenty.asm.BOPFMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:35 AM] [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:35 AM] [WARNING] [ForgeModLoader] The coremod denoflionsx.denLib.CoreMod.denLibCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:35 AM] [WARNING] [ForgeModLoader] The coremod denoflionsx.DenPipes.Core.DenPipesCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:36 AM] [WARNING] [ForgeModLoader] The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:36 AM] [WARNING] [ForgeModLoader] The coremod chylex.java7check.JavaCheckerCoremod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:36 AM] [WARNING] [ForgeModLoader] The coremod logisticspipes.asm.LogisticsPipesCoreLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:36 AM] [WARNING] [ForgeModLoader] The coremod mekanism.common.asm.LoadingHook does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:36 AM] [WARNING] [ForgeModLoader] The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:36 AM] [WARNING] [ForgeModLoader] The coremod mcp.mobius.mobiuscore.asm.CoreDescription does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:36 AM] [WARNING] [ForgeModLoader] The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:36 AM] [WARNING] [ForgeModLoader] The coremod openblocks.OpenBlocksCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:36 AM] [WARNING] [ForgeModLoader] The coremod openeye.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:36 AM] [WARNING] [ForgeModLoader] The coremod openmods.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:36 AM] [WARNING] [ForgeModLoader] The coremod denoflionsx.PluginsforForestry.Core.CoreMod.PfFCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:36 AM] [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:36 AM] [WARNING] [ForgeModLoader] The coremod mrtjp.projectred.compatibility.CompatibilityCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:36 AM] [WARNING] [ForgeModLoader] The coremod lumien.randomthings.Transformer.RTLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:36 AM] [WARNING] [ForgeModLoader] The coremod com.dynious.refinedrelocation.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:36 AM] [WARNING] [ForgeModLoader] The coremod resonant.core.ResonantPluginLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:36 AM] [WARNING] [ForgeModLoader] The coremod tconstruct.preloader.TConstructLoaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:36 AM] [INFO] [TCon-Preloader] Scalpel. Suction. Lumber axe. CLEAR! *zap*
[07/6/2015 08:00:36 AM] [INFO] [TCon-Preloader] Constructing preloader (Modules: [tconstruct.preloader.AccessTransformers, tconstruct.preloader.ASMInterfaceRepair])
[07/6/2015 08:00:36 AM] [INFO] [TCon-Preloader] Found a properties file. Attempting load...
[07/6/2015 08:00:36 AM] [INFO] [TCon-Preloader] Loaded properties successfully. Using specified settings.
[07/6/2015 08:00:36 AM] [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[07/6/2015 08:00:36 AM] [INFO] [ForgeModLoader] Calling tweak class com.mumfrey.liteloader.launch.LiteLoaderTweaker
[07/6/2015 08:00:36 AM] [INFO] [ForgeModLoader] Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[07/6/2015 08:00:36 AM] [INFO] [ForgeModLoader] Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[07/6/2015 08:00:36 AM] [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[07/6/2015 08:00:36 AM] [SEVERE] [ForgeModLoader] Unable to launch
[07/6/2015 08:00:36 AM] java.util.ConcurrentModificationException
[07/6/2015 08:00:36 AM] 	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
[07/6/2015 08:00:36 AM] 	at java.util.ArrayList$Itr.remove(Unknown Source)
[07/6/2015 08:00:36 AM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
[07/6/2015 08:00:36 AM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
[07/6/2015 08:00:36 AM] Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[07/6/2015 08:00:36 AM] Checking for updated files!
[07/6/2015 08:00:37 AM] No updates found!

**Comment by evknucklehead** [comment]
First of all, this is not the help page for the Yogscast pack or the ATLauncher in general. This is for the CrackPack.

That said, your problem is a bug in Forge for MC 1.6.4 that causes crashes with Java 8. There is a sticky post on the ATLauncher Forum's support section that shows how to fix the problem.
