### ISSUE TITLE
issues with update to 2.0.2.0

### ISSUE THREAD

**Issue by pascalprinz** [sciguyryan/TheCrackPack#747]
I've downloaded the server mods with the AT Launcher, deleted the old folders config, libraries, mods and scripts and uploaded the new ones. 

Now, when i try to start the server, i receive the following crash report:
Description: Exception in server tick loop

cpw.mods.fml.common.MissingModsException
	at cpw.mods.fml.common.Loader.sortModList(Loader.java:244)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:472)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
http://pastebin.com/JNSPM6B4

and here the fml-server-latest log:
https://dl.dropboxusercontent.com/u/8622894/fml-server-3.log 

Baubles is requesting a newer version of forge, i've downloaded the latest version for Minecraft 1.7.10 universal, but that has not solved my problem. 

I've also downloaded the server package from the launcher again, but that has not solved my problem as well.

**Comment by evknucklehead** [comment]
It sounds to me that you're running into a problem with the mod list stored in the world save having mods that FML is no longer detecting. There were a couple mods removed between 2.0.1.0 and 2.0.2.0. Without a proper link to the 2.0.2.0 change log, I can't say for sure why they were removed. 

As for how to solve it, there are a couple of options. The first, which is easiest and most likely to work, but will undo any of your work in that world, is to do a completely clean install of the server. That unfortunately means deleting your world save too, which is probably not the best option.

The other, more involved option, is to open the world save in NBTExplorer and find the mod list, removing the entries that are no longer present in the current version. This obviously requires more work, but it will likely allow you to keep your existing world intact. 

Now that 2.0.3.0 has been released, with a newer version of Forge, the Baubles problem should go away.
