### ISSUE TITLE
Problems with Crackpack server 2030

### ISSUE THREAD

**Issue by Ryloon** [sciguyryan/TheCrackPack#748]
[13:39:10] [Server thread/INFO]: Starting minecraft server version 1.7.10
[13:39:10] [Server console handler/ERROR]: Exception handling console input
java.io.IOException: The handle is invalid
	at java.io.FileInputStream.readBytes(Native Method) ~[?:1.7.0_45]
	at java.io.FileInputStream.read(Unknown Source) ~[?:1.7.0_45]
	at java.io.BufferedInputStream.read1(Unknown Source) ~[?:1.7.0_45]
	at java.io.BufferedInputStream.read(Unknown Source) ~[?:1.7.0_45]
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source) ~[?:1.7.0_45]
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source) ~[?:1.7.0_45]
	at sun.nio.cs.StreamDecoder.read(Unknown Source) ~[?:1.7.0_45]
	at java.io.InputStreamReader.read(Unknown Source) ~[?:1.7.0_45]
	at java.io.BufferedReader.fill(Unknown Source) ~[?:1.7.0_45]
	at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.7.0_45]
	at java.io.BufferedReader.readLine(Unknown Source) ~[?:1.7.0_45]
	at net.minecraft.server.dedicated.DedicatedServer$2.run(DedicatedServer.java:97) [lv.class:?]

----------------------------------------------------------------------------------------------------------------------------------

**Comment by jberkers42** [comment]
Any chance of the full log (-latest)?

**Comment by Ryloon** [comment]
Oh sorry, this should be enough

[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NoClassDefFoundError: tconstruct/armor/TinkerArmorEvents
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at tconstruct.armor.TinkerArmor.preInit(TinkerArmor.java:81)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 38 more
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: tconstruct.armor.TinkerArmorEvents
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 39 more
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.OutOfMemoryError: PermGen space
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at tconstruct.armor.TinkerArmor.preInit(TinkerArmor.java:81)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at mantle.pulsar.control.PulseManager.findAndInvokeHandlers(PulseManager.java:235)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at mantle.pulsar.control.PulseManager.preInit(PulseManager.java:189)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at tconstruct.TConstruct.preInit(TConstruct.java:161)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:40:20] [Server thread/DEBUG] [PulseManager-TConstruct/TConstruct]: Preinitialising Pulse Tinkers' Weaponry...
[13:40:20] [Server thread/WARN] [PulseManager-TConstruct/TConstruct]: Caught exception in findAndInvokeHandlers: java.lang.reflect.InvocationTargetException
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at mantle.pulsar.control.PulseManager.findAndInvokeHandlers(PulseManager.java:235)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at mantle.pulsar.control.PulseManager.preInit(PulseManager.java:189)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at tconstruct.TConstruct.preInit(TConstruct.java:161)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NoClassDefFoundError: tconstruct/tools/items/Bowstring
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at tconstruct.weaponry.TinkerWeaponry.registerItems(TinkerWeaponry.java:143)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at tconstruct.weaponry.TinkerWeaponry.preInit(TinkerWeaponry.java:102)
[13:40:20] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 38 more
[13:40:21] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: tconstruct.tools.items.Bowstring
[13:40:21] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[13:40:21] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[13:40:21] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[13:40:21] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 40 more
[13:40:21] [Server thread/INFO] [STDERR/TConstruct]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.OutOfMemoryError: PermGen space
[13:40:21] [Server thread/DEBUG] [PulseManager-TConstruct/TConstruct]: Preinitialising Pulse Tinkers Thaumcraft Compatibility...
[13:40:21] [Server thread/DEBUG] [PulseManager-TConstruct/TConstruct]: Preinitialising Pulse Tinkers Waila Compatibility...
[13:40:21] [Server thread/DEBUG] [PulseManager-TConstruct/TConstruct]: Preinitialising Pulse Tinkers BuildCraft Compatibility...
[13:40:21] [Server thread/DEBUG] [PulseManager-TConstruct/TConstruct]: Preinitialising Pulse Tinkers AE2 Compatibility...
[13:40:21] [Server thread/DEBUG] [PulseManager-TConstruct/TConstruct]: Preinitialising Pulse Tinkers MFR Compatibility...
[13:40:21] [Server thread/DEBUG] [PulseManager-TConstruct/TConstruct]: Preinitialising Pulse Tinkers TE4 Compatibility...
[13:40:21] [Server thread/DEBUG] [PulseManager-TConstruct/TConstruct]: Preinitialising Pulse Tinkers FMP Compatibility...
[13:40:21] [Server thread/TRACE] [TConstruct/TConstruct]: Sent event FMLPreInitializationEvent to mod TConstruct
[13:40:21] [Server thread/TRACE] [Metallurgy/Metallurgy]: Sending event FMLPreInitializationEvent to mod Metallurgy
[13:40:22] [Server thread/TRACE] [Metallurgy/Metallurgy]: Sent event FMLPreInitializationEvent to mod Metallurgy
[13:40:22] [Server thread/ERROR] [ExtraTiC/]: Skipping event FMLPreInitializationEvent and marking errored mod ExtraTiC since required dependency TConstruct has errored
[13:40:22] [Server thread/TRACE] [ExtraUtilities/ExtraUtilities]: Sending event FMLPreInitializationEvent to mod ExtraUtilities
[13:40:22] [Server thread/TRACE] [ExtraUtilities/ExtraUtilities]: Sent event FMLPreInitializationEvent to mod ExtraUtilities
[13:40:22] [Server thread/TRACE] [factorization.notify/factorization.notify]: Sending event FMLPreInitializationEvent to mod factorization.notify
[13:40:22] [Server thread/TRACE] [factorization.notify/factorization.notify]: Sent event FMLPreInitializationEvent to mod factorization.notify
[13:40:22] [Server thread/TRACE] [factorization/factorization]: Sending event FMLPreInitializationEvent to mod factorization
[13:40:22] [Server thread/INFO] [factorization/factorization]: This is Factorization 1.7.10-0.8.88.7
[13:40:22] [Server thread/TRACE] [factorization/factorization]: Sent event FMLPreInitializationEvent to mod factorization
[13:40:22] [Server thread/ERROR] [factorization.misc/]: Skipping event FMLPreInitializationEvent and marking errored mod factorization.misc since required dependency factorization has errored
[13:40:22] [Server thread/TRACE] [FastCraft/FastCraft]: Sending event FMLPreInitializationEvent to mod FastCraft
[13:40:25] [Server thread/TRACE] [FastCraft/FastCraft]: Sent event FMLPreInitializationEvent to mod FastCraft
[13:40:25] [Server thread/TRACE] [Steamcraft/Steamcraft]: Sending event FMLPreInitializationEvent to mod Steamcraft
[13:40:27] [Server thread/TRACE] [Steamcraft/Steamcraft]: Sent event FMLPreInitializationEvent to mod Steamcraft
[13:40:27] [Server thread/TRACE] [flora/flora]: Sending event FMLPreInitializationEvent to mod flora
[13:40:27] [Server thread/TRACE] [flora/flora]: Sent event FMLPreInitializationEvent to mod flora
[13:40:27] [Server thread/TRACE] [ThaumicTinkerer/ThaumicTinkerer]: Sending event FMLPreInitializationEvent to mod ThaumicTinkerer
[13:40:32] [Server thread/TRACE] [ThaumicTinkerer/ThaumicTinkerer]: Sent event FMLPreInitializationEvent to mod ThaumicTinkerer
[13:40:34] [Server thread/TRACE] [ForbiddenMagic/ForbiddenMagic]: Sending event FMLPreInitializationEvent to mod ForbiddenMagic
[13:40:40] [Server thread/TRACE] [ForbiddenMagic/ForbiddenMagic]: Sent event FMLPreInitializationEvent to mod ForbiddenMagic
[13:40:40] [Server thread/TRACE] [foxlib/foxlib]: Sending event FMLPreInitializationEvent to mod foxlib
[13:40:40] [Server thread/TRACE] [foxlib/foxlib]: Sent event FMLPreInitializationEvent to mod foxlib
[13:40:40] [Server thread/TRACE] [funkylocomotion/funkylocomotion]: Sending event FMLPreInitializationEvent to mod funkylocomotion
[13:40:42] [Server thread/TRACE] [funkylocomotion/funkylocomotion]: Sent event FMLPreInitializationEvent to mod funkylocomotion
[13:40:42] [Server thread/ERROR] [FZAddons/]: Skipping event FMLPreInitializationEvent and marking errored mod FZAddons since required dependency factorization has errored
[13:40:42] [Server thread/TRACE] [GalacticraftCore/GalacticraftCore]: Sending event FMLPreInitializationEvent to mod GalacticraftCore
[13:41:05] [Server thread/TRACE] [GalacticraftCore/GalacticraftCore]: Sent event FMLPreInitializationEvent to mod GalacticraftCore
[13:41:05] [Server thread/ERROR] [GalacticraftMars/]: Skipping event FMLPreInitializationEvent and marking errored mod GalacticraftMars since required dependency GalacticraftCore has errored
[13:41:05] [Server thread/TRACE] [advgenerators/advgenerators]: Sending event FMLPreInitializationEvent to mod advgenerators
[13:41:20] [Server thread/TRACE] [advgenerators/advgenerators]: Sent event FMLPreInitializationEvent to mod advgenerators
[13:41:20] [Server thread/TRACE] [Growthcraft/Growthcraft]: Sending event FMLPreInitializationEvent to mod Growthcraft
[13:41:24] [Server thread/TRACE] [Growthcraft/Growthcraft]: Sent event FMLPreInitializationEvent to mod Growthcraft
[13:41:24] [Server thread/ERROR] [Growthcraft|Cellar/]: Skipping event FMLPreInitializationEvent and marking errored mod Growthcraft|Cellar since required dependency Growthcraft has errored
[13:41:24] [Server thread/ERROR] [Growthcraft|Apples/]: Skipping event FMLPreInitializationEvent and marking errored mod Growthcraft|Apples since required dependency Growthcraft has errored
[13:41:24] [Server thread/ERROR] [Growthcraft|Bamboo/]: Skipping event FMLPreInitializationEvent and marking errored mod Growthcraft|Bamboo since required dependency Growthcraft has errored
[13:41:28] [Server thread/ERROR] [Growthcraft|Bees/]: Skipping event FMLPreInitializationEvent and marking errored mod Growthcraft|Bees since required dependency Growthcraft has errored
[13:41:28] [Server thread/ERROR] [Growthcraft|Fishtrap/]: Skipping event FMLPreInitializationEvent and marking errored mod Growthcraft|Fishtrap since required dependency Growthcraft has errored
[13:41:32] [Server thread/ERROR] [Growthcraft|Grapes/]: Skipping event FMLPreInitializationEvent and marking errored mod Growthcraft|Grapes since required dependency Growthcraft has errored
[13:41:32] [Server thread/ERROR] [Growthcraft|Hops/]: Skipping event FMLPreInitializationEvent and marking errored mod Growthcraft|Hops since required dependency Growthcraft has errored
[13:41:32] [Server thread/ERROR] [Growthcraft|Rice/]: Skipping event FMLPreInitializationEvent and marking errored mod Growthcraft|Rice since required dependency Growthcraft has errored
[13:41:32] [Server thread/TRACE] [HardcoreEnderExpansion/HardcoreEnderExpansion]: Sending event FMLPreInitializationEvent to mod HardcoreEnderExpansion

**Comment by Ryloon** [comment]
Sorry, not so good at this (as you can see). Pastebin didn't allow me to post the whole log, so i uploaded it to mediafire. Might be the worst possible way to share it, but owell. https://www.mediafire.com/?1211v00izbldiey

**Comment by EndercraftO** [comment]
I have a problem that all modded items will disappear after right clicking or breaking

**Comment by jberkers42** [comment]
@EndercraftO, it sounds like you have a modded client connecting to a vanilla server.  You need to start the server using the LaunchServer.bat or LaunchServer.sh (depending on your operating system).  If you are using a hosting service, you need to ensure that the directory structure is completely uploaded, and that you use the fml jar, not the vanilla one.
