### ISSUE TITLE
LaunchServer.bat Help

### ISSUE THREAD

**Issue by XICELEOPARDX** [sciguyryan/TheCrackPack#757]
When I Start The .bat File This Happens-
earsenal.item.tool.ItemWrenchRF
[20:23:17] [Server thread/INFO] [CoFH ASM]: Stripping methods and fields from re
dstonearsenal.item.tool.ItemWrenchRF
[20:23:17] [Server thread/INFO] [CoFH ASM]: Adding runtime interfaces to redston
earsenal.item.tool.ItemWrenchBattleRF
[20:23:17] [Server thread/INFO] [CoFH ASM]: Stripping methods and fields from re
dstonearsenal.item.tool.ItemWrenchBattleRF
[20:23:17] [CoFHUpdater:RedstoneArsenal/WARN] [RedstoneArsenal]: Update check fo
r Redstone Arsenal failed.
java.io.FileNotFoundException: https://raw.githubusercontent.com/CoFH/RedstoneAr
senal/master/VERSION
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown So
urce) ~[?:1.7.0_72]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unkn
own Source) ~[?:1.7.0_72]
        at java.net.URL.openStream(Unknown Source) ~[?:1.7.0_72]
        at cofh.mod.updater.UpdateCheckThread.run(UpdateCheckThread.java:44) [Up
dateCheckThread.class:?]
[20:23:17] [Thread-8/INFO] [RefinedRelocation]: Version Checker Status: CURRENT
[20:23:18] [Server thread/INFO] [simplyjetpacks]: Starting Simply Jetpacks
[20:23:18] [Server thread/INFO] [simplyjetpacks]: Loading configuration files
[20:23:18] [Server thread/INFO] [simplyjetpacks]: Constructing items
[20:23:18] [Server thread/INFO] [simplyjetpacks]: Registering items
[20:23:18] [Server thread/INFO] [simplyjetpacks]: Registering handlers
[20:23:18] [Server thread/INFO] [SolarFlux]: Pre Initialization
[20:23:18] [Server thread/INFO] [SolarFlux]: Initialization of configuration
[20:23:18] [Server thread/INFO] [SolarFlux]: Registering blocks
[20:23:18] [Server thread/INFO] [SolarFlux]: Registering items
[20:23:19] [Server thread/INFO] [STDOUT]: [vswe.stevescarts.Blocks.ModBlocks:ini
t:89]: Failed to create block (BlockDistributor)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]: java.lang.IllegalArgumentException: Duplicate id: distributor
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at net.minecraft.tileentity.TileEntity.func_145826_a(TileEntity.
java:43)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at cpw.mods.fml.common.registry.GameRegistry.registerTileEntity(
GameRegistry.java:275)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at vswe.stevescarts.Blocks.ModBlocks.init(ModBlocks.java:83)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at vswe.stevescarts.StevesCarts.preInit(StevesCarts.java:87)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Sourc
e)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLMo
dContainer.java:513)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Sourc
e)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at com.google.common.eventbus.EventSubscriber.handleEvent(EventS
ubscriber.java:74)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at com.google.common.eventbus.SynchronizedEventSubscriber.handle
Event(SynchronizedEventSubscriber.java:47)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at com.google.common.eventbus.EventBus.dispatch(EventBus.java:32
2)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at com.google.common.eventbus.EventBus.dispatchQueuedEvents(Even
tBus.java:304)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at cpw.mods.fml.common.LoadController.sendEventToModContainer(Lo
adController.java:208)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at cpw.mods.fml.common.LoadController.propogateStateMessage(Load
Controller.java:187)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Sourc
e)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at com.google.common.eventbus.EventSubscriber.handleEvent(EventS
ubscriber.java:74)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at com.google.common.eventbus.SynchronizedEventSubscriber.handle
Event(SynchronizedEventSubscriber.java:47)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at com.google.common.eventbus.EventBus.dispatch(EventBus.java:32
2)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at com.google.common.eventbus.EventBus.dispatchQueuedEvents(Even
tBus.java:304)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at cpw.mods.fml.common.LoadController.distributeStateMessage(Loa
dController.java:118)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)

[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLSe
rverHandler.java:88)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonH
andler.java:314)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(D
edicatedServer.java:117)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java
:387)
[20:23:19] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.ja
va:685)
[20:23:20] [Server thread/INFO] [STDOUT]: [kihira.tails.common.FoxLibManager:isF
oxlibCorrectVersion:102]: 1.7.10-0.6.0
[20:23:20] [Server thread/INFO] [TMechworks]: Loading configuration...
[20:23:20] [Server thread/INFO] [TMechworks]: Done.
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 33 alr
eady occupided by Flight is being overwriting with witchery:potion.paralysed, yo
u may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 34 alr
eady occupided by Feather Fall is being overwriting with witchery:potion.wrapped
invine, you may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 35 alr
eady occupided by Haste is being overwriting with witchery:potion.spiked, you ma
y want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 36 alr
eady occupided by True Sight is being overwriting with witchery:potion.sprouting
, you may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 37 alr
eady occupided by Regeneration is being overwriting with witchery:potion.grotesq
ue, you may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 38 alr
eady occupided by Magic Shield is being overwriting with witchery:potion.love, y
ou may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 39 alr
eady occupided by Charmed is being overwriting with witchery:potion.allergysun,
you may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 40 alr
eady occupided by Frost Slow is being overwriting with witchery:potion.chilled,
you may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 41 alr
eady occupided by Chrono Anchor is being overwriting with witchery:potion.snowtr
ail, you may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 42 alr
eady occupided by Mana Regen is being overwriting with witchery:potion.floating,
 you may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 43 alr
eady occupided by Entangled is being overwriting with witchery:potion.hellishaur
a, you may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 44 alr
eady occupided by Watery Grave is being overwriting with witchery:potion.brewing
expertise, you may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 45 alr
eady occupided by Spell Reflect is being overwriting with witchery:potion.double
jump, you may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 46 alr
eady occupided by Silence is being overwriting with witchery:potion.featherfall,
 you may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 47 alr
eady occupided by Swift Swim is being overwriting with witchery:potion.allergyda
rk, you may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 48 alr
eady occupided by Agility is being overwriting with witchery:potion.reincarnate,
 you may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 49 alr
eady occupided by Leap is being overwriting with witchery:potion.insane, you may
 want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 51 alr
eady occupided by Astral Distortion is being overwriting with witchery:potion.ke
epinventory, you may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 52 alr
eady occupided by Mana Shield is being overwriting with witchery:potion.sinking,
 you may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 53 alr
eady occupided by Fury is being overwriting with witchery:potion.overheating, yo
u may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 54 alr
eady occupided by Scramble Synapses is being overwriting with witchery:potion.wa
kingnightmare, you may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 55 alr
eady occupided by Illuminated is being overwriting with witchery:potion.queasy,
you may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 56 alr
eady occupided by Greater Mana Restoration is being overwriting with witchery:po
tion.swimming, you may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 57 alr
eady occupided by Epic Mana Restoration is being overwriting with witchery:potio
n.resizing, you may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 58 alr
eady occupided by Legendary Mana Restoration is being overwriting with witchery:
potion.colorful, you may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 59 alr
eady occupided by Gravity Well is being overwriting with witchery:potion.enderin
hibition, you may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 60 alr
eady occupided by Levitation is being overwriting with witchery:potion.illfittin
g, you may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 61 alr
eady occupided by Clarity is being overwriting with witchery:potion.volatility,
you may want to change potion ids in the config file!
[20:23:21] [Server thread/WARN] [witchery: SERVER]: witchery: Potion slot 62 alr
eady occupided by Shrunken is being overwriting with witchery:potion.enslaved, y
ou may want to change potion ids in the config file!
[20:23:23] [Server thread/INFO] [Railcraft]: Automation Module: Ore Detected, ad
ding to blocks Tunnel Bore can mine: treeSapling, id=1xtile.witchery:witchsaplin
g@32767 meta=32,767
[20:23:23] [Server thread/INFO] [Railcraft]: Automation Module: Ore Detected, ad
ding to blocks Tunnel Bore can mine: logWood, id=1xtile.witchery:witchlog@32767
meta=32,767
[20:23:23] [Server thread/INFO] [Railcraft]: Automation Module: Ore Detected, ad
ding to blocks Tunnel Bore can mine: treeLeaves, id=1xtile.witchery:witchleaves@
32767 meta=32,767
[20:23:24] [Server thread/ERROR] [ForgeMicroblock]: Invalid line in microblocks.
cfg: "Mariculture:woods:0-2
[20:23:24] [Server thread/ERROR] [ForgeMicroblock]: Unmatched quotes
[20:23:24] [Server thread/ERROR] [ForgeMicroblock]: Invalid line in microblocks.
cfg: "Metallurgy:base.block"0-7
[20:23:24] [Server thread/ERROR] [ForgeMicroblock]: Name must be followed by a c
olon separator
[20:23:24] [Server thread/ERROR] [ForgeMicroblock]: Invalid line in microblocks.
cfg: "Metallurgy:base.brick"0-7
[20:23:24] [Server thread/ERROR] [ForgeMicroblock]: Name must be followed by a c
olon separator
[20:23:24] [Server thread/ERROR] [ForgeMicroblock]: Invalid line in microblocks.
cfg: "Metallurgy:ender.block"0-2
[20:23:24] [Server thread/ERROR] [ForgeMicroblock]: Name must be followed by a c
olon separator
[20:23:24] [Server thread/ERROR] [ForgeMicroblock]: Invalid line in microblocks.
cfg: "Metallurgy:ender.brick"0-2
[20:23:24] [Server thread/ERROR] [ForgeMicroblock]: Name must be followed by a c
olon separator
[20:23:24] [Server thread/ERROR] [ForgeMicroblock]: Invalid line in microblocks.
cfg: "Metallurgy:fantasy.block"0-15
[20:23:24] [Server thread/ERROR] [ForgeMicroblock]: Name must be followed by a c
olon separator
[20:23:24] [Server thread/ERROR] [ForgeMicroblock]: Invalid line in microblocks.
cfg: "Metallurgy:fantasy.brick"0-15
[20:23:24] [Server thread/ERROR] [ForgeMicroblock]: Name must be followed by a c
olon separator
[20:23:24] [Server thread/ERROR] [ForgeMicroblock]: Invalid line in microblocks.
cfg: "Metallurgy:nether.block"0-12
[20:23:24] [Server thread/ERROR] [ForgeMicroblock]: Name must be followed by a c
olon separator
[20:23:24] [Server thread/ERROR] [ForgeMicroblock]: Invalid line in microblocks.
cfg: "Metallurgy:nether.brick"0-12
[20:23:24] [Server thread/ERROR] [ForgeMicroblock]: Name must be followed by a c
olon separator
[20:23:24] [Server thread/ERROR] [ForgeMicroblock]: Invalid line in microblocks.
cfg: "Metallurgy:precious.block"0-4
[20:23:24] [Server thread/ERROR] [ForgeMicroblock]: Name must be followed by a c
olon separator
[20:23:24] [Server thread/ERROR] [ForgeMicroblock]: Invalid line in microblocks.
cfg: "Metallurgy:precious.brick"0-4
[20:23:24] [Server thread/ERROR] [ForgeMicroblock]: Name must be followed by a c
olon separator
[20:23:24] [Server thread/ERROR] [ForgeMicroblock]: Invalid line in microblocks.
cfg: "Metallurgy:vanilla.brick"0-1
[20:23:24] [Server thread/ERROR] [ForgeMicroblock]: Name must be followed by a c
olon separator
[20:23:24] [Server thread/INFO] [FML]: Applying holder lookups
[20:23:24] [Server thread/WARN] [FML]: Unable to lookup CompactMachines:interfac
eblock for public static org.dave.CompactMachines.block.BlockCM org.dave.Compact
Machines.init.ModBlocks.interfaceblock. Is there something wrong with the regist
ry?
[20:23:24] [Server thread/INFO] [FML]: Holder lookups applied
[20:23:24] [Server thread/INFO]: Loading properties
[20:23:24] [Server thread/INFO]: You need to agree to the EULA in order to run t
he server. Go to eula.txt for more info.
[20:23:24] [Server thread/WARN] [FML]: Can't revert to frozen GameData state wit
hout freezing first.
[20:23:24] [Server thread/INFO] [FML]: Applying holder lookups
[20:23:24] [Server thread/WARN] [FML]: Unable to lookup CompactMachines:interfac
eblock for public static org.dave.CompactMachines.block.BlockCM org.dave.Compact
Machines.init.ModBlocks.interfaceblock. Is there something wrong with the regist
ry?
[20:23:24] [Server thread/INFO] [FML]: Holder lookups applied
[20:23:24] [Server thread/INFO] [STDOUT]: [scala.Console$:println:148]: Stopped
[20:23:24] [Server thread/WARN] [EnderIO]: Failed to write Transciever Channels
on exit: java.util.concurrent.ExecutionException: java.lang.NullPointerException

[20:23:24] [Server thread/ERROR] [HatStand]: Skipping event FMLServerStoppedEven
t and marking errored mod HatStand since required dependency Hats has errored
[20:23:24] [Server thread/INFO] [FML]: The state engine was in incorrect state E
RRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[20:23:24] [Server thread/INFO] [FML]: The state engine was in incorrect state E
RRORED and forced into state AVAILABLE. Errors may have been discarded.
Press any key to continue . . .

**Comment by iKurama** [comment]
You need to agree to the EULA!

**Comment by XICELEOPARDX** [comment]
How do I do that

**Comment by XICELEOPARDX** [comment]
Thank you
