### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by DoneganSkye** [sciguyryan/TheCrackPack#812]
Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859) ~[?:1.7.0_71]
at java.util.ArrayList$Itr.next(ArrayList.java:831) ~[?:1.7.0_71]
at micdoodle8.mods.galacticraft.api.prefab.entity.EntitySpaceshipBase.func_70071_h_(EntitySpaceshipBase.java:199) ~[EntitySpaceshipBase.class:?]
at micdoodle8.mods.galacticraft.api.prefab.entity.EntityAutoRocket.func_70071_h_(EntityAutoRocket.java:326) ~[EntityAutoRocket.class:?]
at micdoodle8.mods.galacticraft.api.prefab.entity.EntityTieredRocket.func_70071_h_(EntityTieredRocket.java:203) ~[EntityTieredRocket.class:?]
at micdoodle8.mods.galacticraft.core.entities.EntityTier1Rocket.func_70071_h_(EntityTier1Rocket.java:45) ~[EntityTier1Rocket.class:?]
at net.minecraft.world.World.func_72866_a(World.java:2070) ~[ahb.class:?]
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648) ~[mt.class:?]
at net.minecraft.world.World.func_72870_g(World.java:2034) ~[ahb.class:?]
at net.minecraft.world.World.func_72939_s(World.java:1887) ~[ahb.class:?]
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]

Im assuming it has to do with the rocket from galacticcraft. But what to do next or how to do it im clueless. please help!

**Comment by evknucklehead** [comment]
You'll need to use NBT Explorer to delete the glitched rocket. The coordinates of the particular rocket, including the dimension it was in at the time, should be listed somewhere in the full crash report.

As for how to prevent the problem from recurring, try to figure out what else in the area was interacting with the rocket when the crash occurred. Sometimes having some form of item or liquid transport near certain blocks or entities will cause this sort of crash.
