### ISSUE TITLE
Crack Pack crashes when screen says building terrain

### ISSUE THREAD

**Issue by WrestlerBlake** [sciguyryan/TheCrackPack#813]
So I was able to play a little before and build myself a little house and then I suddenly crashed. I tried to restart it and now when I click play it starts loading and then crashes and checks for updates. Here is the log.

[21/2/2015 15:56:38 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[21/2/2015 15:56:38 PM] ---------------------------------------------------------------------------------------
[21/2/2015 15:56:38 PM] 
[21/2/2015 15:56:38 PM] -- Head --
[21/2/2015 15:56:38 PM] Stacktrace:
[21/2/2015 15:56:38 PM] 	at java.io.DataInputStream.readUTF(Unknown Source)
[21/2/2015 15:56:38 PM] 	at java.io.DataInputStream.readUTF(Unknown Source)
[21/2/2015 15:56:38 PM] 	at net.minecraft.nbt.NBTTagCompound.func_152448_b(SourceFile:322)
[21/2/2015 15:56:38 PM] 	at net.minecraft.nbt.NBTTagCompound.func_152446_a(SourceFile:38)
[21/2/2015 15:56:38 PM] 
[21/2/2015 15:56:38 PM] -- NBT Tag --
[21/2/2015 15:56:38 PM] Details:
[21/2/2015 15:56:38 PM] 	Tag name: Level
[21/2/2015 15:56:38 PM] 	Tag type: 10
[21/2/2015 15:56:38 PM] Stacktrace:
[21/2/2015 15:56:38 PM] 	at net.minecraft.nbt.NBTTagCompound.func_152449_a(SourceFile:329)
[21/2/2015 15:56:38 PM] 	at net.minecraft.nbt.NBTTagCompound.func_152446_a(SourceFile:41)
[21/2/2015 15:56:38 PM] 	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:168)
[21/2/2015 15:56:38 PM] 	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:125)
[21/2/2015 15:56:38 PM] 	at net.minecraft.nbt.CompressedStreamTools.func_74794_a(CompressedStreamTools.java:120)
[21/2/2015 15:56:38 PM] 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:121)
[21/2/2015 15:56:38 PM] 	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:20)
[21/2/2015 15:56:38 PM] 	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:12)
[21/2/2015 15:56:38 PM] 	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:343)
[21/2/2015 15:56:38 PM] 	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
[21/2/2015 15:56:38 PM] 	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
[21/2/2015 15:56:38 PM] 	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
[21/2/2015 15:56:38 PM] 	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
[21/2/2015 15:56:38 PM] 	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265)
[21/2/2015 15:56:38 PM] 	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:78)
[21/2/2015 15:56:38 PM] 	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
[21/2/2015 15:56:38 PM] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
[21/2/2015 15:56:38 PM] 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[21/2/2015 15:56:38 PM] 
[21/2/2015 15:56:38 PM] -- System Details --
[21/2/2015 15:56:38 PM] Details:
[21/2/2015 15:56:38 PM] 	Minecraft Version: 1.7.10
[21/2/2015 15:56:38 PM] 	Operating System: Windows 7 (amd64) version 6.1
[21/2/2015 15:56:38 PM] 	Java Version: 1.7.0_75, Oracle Corporation
[21/2/2015 15:56:38 PM] 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[21/2/2015 15:56:38 PM] 	Memory: 2462624752 bytes (2348 MB) / 3688366080 bytes (3517 MB) up to 4225236992 bytes (4029 MB)
[21/2/2015 15:56:38 PM] 	Mod Pack: Unknown / None
[21/2/2015 15:56:38 PM] 	LiteLoader Mods: 1 loaded mod(s)
[21/2/2015 15:56:38 PM]           - VoxelMap version 1.2.3
[21/2/2015 15:56:38 PM] 	LaunchWrapper: 56 active transformer(s)
[21/2/2015 15:56:38 PM]           - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
[21/2/2015 15:56:38 PM]           - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
[21/2/2015 15:56:38 PM]           - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
[21/2/2015 15:56:38 PM]           - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
[21/2/2015 15:56:38 PM]           - Transformer: appeng.transformer.asm.ASMIntegration
[21/2/2015 15:56:38 PM]           - Transformer: codechicken.lib.asm.ClassHeirachyManager
[21/2/2015 15:56:38 PM]           - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
[21/2/2015 15:56:38 PM]           - Transformer: codechicken.core.asm.TweakTransformer
[21/2/2015 15:56:38 PM]           - Transformer: codechicken.core.asm.DelegatedTransformer
[21/2/2015 15:56:38 PM]           - Transformer: codechicken.core.asm.DefaultImplementationTransformer
[21/2/2015 15:56:38 PM]           - Transformer: cofh.asm.TransformerCore
[21/2/2015 15:56:38 PM]           - Transformer: cofh.asm.PCCASMTransformer
[21/2/2015 15:56:38 PM]           - Transformer: fastcraft.asm.FastCraftTransformer
[21/2/2015 15:56:38 PM]           - Transformer: mariculture.fishery.VanillaOverride
[21/2/2015 15:56:38 PM]           - Transformer: micdoodle8.mods.miccore.MicdoodleTransformer
[21/2/2015 15:56:38 PM]           - Transformer: mcp.mobius.mobiuscore.asm.CoreTransformer
[21/2/2015 15:56:38 PM]           - Transformer: codechicken.nei.asm.NEITransformer
[21/2/2015 15:56:38 PM]           - Transformer: li.cil.oc.common.asm.ClassTransformer
[21/2/2015 15:56:38 PM]           - Transformer: thaumic.tinkerer.preloader.AccessTransformer
[21/2/2015 15:56:38 PM]           - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
[21/2/2015 15:56:38 PM]           - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
[21/2/2015 15:56:38 PM]           - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
[21/2/2015 15:56:38 PM]           - Transformer: factorization.coremod.ASMTransformer
[21/2/2015 15:56:38 PM]           - Transformer: openmods.OpenModsClassTransformer
[21/2/2015 15:56:38 PM]           - Transformer: openblocks.asm.OpenBlocksClassTransformer
[21/2/2015 15:56:38 PM]           - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
[21/2/2015 15:56:38 PM]           - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
[21/2/2015 15:56:38 PM]           - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
[21/2/2015 15:56:38 PM]           - Transformer: appeng.transformer.asm.ASMTweaker
[21/2/2015 15:56:38 PM]           - Transformer: aroma1997.core.coremod.asm.AromaAccessTransformer
[21/2/2015 15:56:38 PM]           - Transformer: pl.asie.lib.core.AsieLibCoremodTransformer
[21/2/2015 15:56:38 PM]           - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
[21/2/2015 15:56:38 PM]           - Transformer: cofh.asm.PCCAccessTransformer
[21/2/2015 15:56:38 PM]           - Transformer: nf.fr.ephys.cookiecore.common.core.CookieCoreAT
[21/2/2015 15:56:38 PM]           - Transformer: factorization.coremod.FzAccessTransformer
[21/2/2015 15:56:38 PM]           - Transformer: net.malisis.core.asm.MalisisCoreAccessTransformer
[21/2/2015 15:56:38 PM]           - Transformer: mariculture.core.AccessTransformers
[21/2/2015 15:56:38 PM]           - Transformer: micdoodle8.mods.miccore.MicdoodleAccessTransformer
[21/2/2015 15:56:38 PM]           - Transformer: thaumic.tinkerer.preloader.AccessTransformer
[21/2/2015 15:56:38 PM]           - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
[21/2/2015 15:56:38 PM]           - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
[21/2/2015 15:56:38 PM]           - Transformer: net.malisis.core.asm.MalisisCoreTransformer
[21/2/2015 15:56:38 PM]           - Transformer: lumien.randomthings.Transformer.RTClassTransformer
[21/2/2015 15:56:38 PM]           - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
[21/2/2015 15:56:38 PM]           - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
[21/2/2015 15:56:38 PM]           - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderCallbackInjectionTransformer
[21/2/2015 15:56:38 PM]           - Transformer: com.mumfrey.liteloader.client.transformers.JoinGamePacketTransformer
[21/2/2015 15:56:38 PM]           - Transformer: com.mumfrey.liteloader.client.transformers.ServerChatPacketTransformer
[21/2/2015 15:56:38 PM]           - Transformer: com.mumfrey.liteloader.client.transformers.LoginSuccessPacketTransformer
[21/2/2015 15:56:38 PM]           - Transformer: com.mumfrey.liteloader.client.transformers.ChatPacketTransformer
[21/2/2015 15:56:38 PM]           - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
[21/2/2015 15:56:38 PM]           - Transformer: com.mumfrey.liteloader.client.transformers.ServerCustomPayloadPacketTransformer
[21/2/2015 15:56:38 PM]           - Transformer: com.mumfrey.liteloader.client.transformers.CustomPayloadPacketTransformer
[21/2/2015 15:56:38 PM]           - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
[21/2/2015 15:56:38 PM]           - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
[21/2/2015 15:56:38 PM]           - Transformer: com.rwtema.extrautils.command.CommandASMCore
[21/2/2015 15:56:38 PM] 	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:-OmitStackTraceInFastThrow -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xms3584M -Xmx4096M -XX:PermSize=256M
[21/2/2015 15:56:38 PM] 	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
[21/2/2015 15:56:38 PM] 	FML{7.10.85.1277} [Forge Mod Loader] (forge-1.7.10-10.13.2.1277-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
[21/2/2015 15:56:38 PM] 	OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
[21/2/2015 15:56:38 PM] 	Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper] (AROMA1997CORE-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
[21/2/2015 15:56:38 PM] 	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BIOMESOPLENTY-1.7.10-2.1.0.1004-UNIVERSAL.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
[21/2/2015 15:56:38 PM] 	Botania{r1.3-149} [Botania] (BOTANIA R1.3-149.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
[21/2/2015 15:56:38 PM] 	UniversalElectricity{@MAJOR@.@MINOR@.@REVIS@} [Universal Electricity] (UNIVERSAL-ELECTRICITY-4.0.0.81-CORE.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
[21/2/2015 15:56:38 PM] 	CompactMachines{1.7.10-1.13} [Compact Machines] (COMPACTMACHINES-1.7.10-1.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
[21/2/2015 15:56:38 PM] 	enhancedportals{3.0.9} [EnhancedPortals] (ENHANCEDPORTALS_1.7.10-UNIVERSAL-3.0.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
[21/2/2015 15:56:38 PM] 	flora{1.0} [Fluids and Liquids on Ridiculous Armor] (FLORA-1.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
[21/2/2015 15:56:38 PM] 	Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar] (GROWTHCRAFT-CELLAR-1.7.10-2.1.0A.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
[21/2/2015 15:56:38 PM] 	HardcoreEnderExpansion{1.6.7} [Hardcore Ender Expansion] (HARDCOREENDEREXPANSION MC-1.7.10 V1.6.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
[21/2/2015 15:56:38 PM] 	Mariculture{1.2.3d} [Mariculture] (MARICULTURE-1.7.10-1.2.3D.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
[21/2/2015 15:56:38 PM] 	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC6} [MFR Compat: ExtraBiomes] (MINEFACTORYRELOADED-[1.7.10]2.8.0RC6-21.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
[21/2/2015 15:56:38 PM] 	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC6} [MFR Compat: Thaumcraft] (MINEFACTORYRELOADED-[1.7.10]2.8.0RC6-21.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
[21/2/2015 15:56:38 PM] 	MineTweaker3{3.0.9B} [MineTweaker 3] (MINETWEAKER3-1.7.10-3.0.9C.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
[21/2/2015 15:56:38 PM] 	recipehandler{0.2} [NoMoreRecipeConflict] (NOMORERECIPECONFLICT-0.2(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
[21/2/2015 15:56:38 PM] 	RandomThings{2.2.3} [Random Things] (RANDOMTHINGS-2.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
[21/2/2015 15:56:38 PM] 	Stackie{1.5.1.30} [Stackie] (STACKIE-1.7.10-1.5.1.30-UNIVERSAL.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
[21/2/2015 15:56:38 PM] 	TooMuchRain{%VERSION%} [TooMuchRain] (TOOMUCHRAIN-1.7.2-1.0.0-B5-UNIVERSAL.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
[21/2/2015 15:56:38 PM] 	Ztones{1.7.10} [Ztones] (ZTONES-1.7.10-2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
[21/2/2015 15:56:38 PM] 	TConstruct Environment: Environment healthy.
[21/2/2015 15:56:38 PM] process has not exited
[21/2/2015 15:56:38 PM] java.lang.ProcessImpl.exitValue(Unknown Source)
[21/2/2015 15:56:38 PM] com.atlauncher.data.Instance$2.run(Instance.java:1185)
[21/2/2015 15:56:38 PM] Checking for updated files!
[21/2/2015 15:56:38 PM] No updates found!

**Comment by evknucklehead** [comment]
Upload a complete log to ATLauncher's upload service and post the link here. While the log you've already provided does tell me that your basic configuration is in good shape, it doesn't tell what was happening when the crash occurred.

My initial suspicion is something has corrupted your world files. How much they were corrupted and why, I can't tell for certain. It may be necessary to start a new world, if the corruption is bad enough.

**Comment by WrestlerBlake** [comment]
Oh ok thank you for answering. I honestly wish I had some more experience with reading log files because I do know some basic programming but log files are a tad overbearing for me. Here is the link.
http://paste.atlauncher.com/view/79af2da2

**Comment by evknucklehead** [comment]
Yeah, it looks like your overworld data has been corrupted, possibly beyond repair. You'll need to either delete the region files for the overworld, or just start a new world.

As for the large number of lines in the log, I don't read all of them. I check the initial loading phases then skip to the end and work my way back until I spot the point where the error occurs.

**Comment by Frankoluscage** [comment]
I have the same problem but it does not have a crash report it just goes back to crackpack and says updating modpack, and yes I deleatied the usercache.json.

**Comment by WrestlerBlake** [comment]
yah I just created a new world. I wasn't very far into that one to be honest so it was no big deal. Also frank deleted that log didn't do anything for me. It recreates itself after you crash again so yah i'd say just create a new world.

**Comment by Frankoluscage** [comment]
ok thanks

**Comment by evknucklehead** [comment]
usercache.json is not the culprit in this case. Your error was because the level.dat file was broken somehow.
