### ISSUE TITLE
Crashes when initializing 

### ISSUE THREAD

**Issue by Sarloos** [sciguyryan/TheCrackPack#823]
The launcher crashes when it's in the phase of initializing the game. I know you want me to post the full log at the (paste.)ATlauncher website, but i can't find anywhere where that is possible. I've tried pastebin to, but the file is apparently to big :/ Because of this, I've pasted the first part and the last part of the log below. Hope it's enough information, if not, i would like some guidance towards how i paste the log at ATlauncher.

btw. here is what i have tried:
   - Allocating up to 6144 MB RAM
   - Updating Java (used the link at ATlauncher) 
   - trying earlier versions. In version 2.0.2.0 the same happens. In version 2.0.1.0 and 2.0.0.0 i get      though to the starting menu, but it then crashes when i try and load up a new world. in version 1.5.1.0 and 1.1.1.0 everything seems to work (but i would of cause like to play the newest version).

FIRST PART:
[23/2/2015 19:17:46 PM] Loading Language: English
[23/2/2015 19:17:46 PM] Loading Language: English
[23/2/2015 19:17:46 PM] ATLauncher Version: 3.2.2.2
[23/2/2015 19:17:46 PM] Operating System: Windows 7
[23/2/2015 19:17:46 PM] RAM Available: 8085MB
[23/2/2015 19:17:46 PM] Java Version: Launcher: 1.7.0_75, Minecraft: 1.7.0_75
[23/2/2015 19:17:46 PM] Java Path: C:\Program Files\Java\jre7
[23/2/2015 19:17:46 PM] 64 Bit Java: true
[23/2/2015 19:17:46 PM] Launcher Directory: **USERSDIR**
[23/2/2015 19:17:46 PM] Using Theme: Default Theme by RyanTheAllmighty
[23/2/2015 19:17:46 PM] Showing splash screen and loading everything
[23/2/2015 19:17:47 PM] Checking for updated files!
[23/2/2015 19:17:47 PM] No updates found!
[23/2/2015 19:17:48 PM] Loading external library authlib-1.5.17.jar to classpath
[23/2/2015 19:17:48 PM] Loading external library log4j-api-2.0-beta9.jar to classpath
[23/2/2015 19:17:48 PM] Loading external library log4j-core-2.0-beta9.jar to classpath
[23/2/2015 19:17:48 PM] Loading external library guava-17.0.jar to classpath
[23/2/2015 19:17:48 PM] Loading external library commons-io-2.4.jar to classpath
[23/2/2015 19:17:48 PM] Loading external library commons-lang3-3.3.2.jar to classpath
[23/2/2015 19:17:48 PM] [Background] Checking Minecraft Versions Started
[23/2/2015 19:17:49 PM] Checking account UUID's!
[23/2/2015 19:17:49 PM] Launcher finished loading everything
[23/2/2015 19:17:49 PM] Launcher opening
[23/2/2015 19:17:49 PM] Made By Bob*
[23/2/2015 19:17:49 PM] *(Not Actually)
[23/2/2015 19:17:49 PM] Setting up Bottom Bar
[23/2/2015 19:17:49 PM] Finished Setting up Bottom Bar
[23/2/2015 19:17:49 PM] Setting up Tabs
[23/2/2015 19:17:51 PM] Finished Setting up Tabs
[23/2/2015 19:17:51 PM] Showing Launcher
[23/2/2015 19:17:52 PM] [Background] Checking Minecraft Versions Complete

LAST PART:
[23/2/2015 19:23:56 PM] [Client thread/ERROR] [FML]: The following problems were captured during this phase
[23/2/2015 19:23:56 PM] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
[23/2/2015 19:23:56 PM] // Everything's going to plan. No, really, that was supposed to happen.
[23/2/2015 19:23:56 PM] 
[23/2/2015 19:23:56 PM] Time: 2/23/15 7:23 PM
[23/2/2015 19:23:56 PM] Description: Initializing game
[23/2/2015 19:23:56 PM] 
[23/2/2015 19:23:56 PM] java.lang.IllegalArgumentException: java.lang.ExceptionInInitializerError
[23/2/2015 19:23:56 PM] 	at factorization.coremod.AtVerifier.verify(AtVerifier.java:55)
[23/2/2015 19:23:56 PM] 	at factorization.shared.Core.validateEnvironment(Core.java:576)
[23/2/2015 19:23:56 PM] 	at factorization.shared.Core.modsLoaded(Core.java:188)
[23/2/2015 19:23:56 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23/2/2015 19:23:56 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23/2/2015 19:23:56 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23/2/2015 19:23:56 PM] 	at java.lang.reflect.Method.invoke(Unknown Source)
[23/2/2015 19:23:56 PM] 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
[23/2/2015 19:23:56 PM] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[23/2/2015 19:23:56 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23/2/2015 19:23:56 PM] 	at java.lang.reflect.Method.invoke(Unknown Source)
[23/2/2015 19:23:56 PM] 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[23/2/2015 19:23:56 PM] 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[23/2/2015 19:23:56 PM] 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[23/2/2015 19:23:56 PM] 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[23/2/2015 19:23:56 PM] 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[23/2/2015 19:23:56 PM] 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
[23/2/2015 19:23:56 PM] 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
[23/2/2015 19:23:56 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23/2/2015 19:23:56 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23/2/2015 19:23:56 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23/2/2015 19:23:56 PM] 	at java.lang.reflect.Method.invoke(Unknown Source)
[23/2/2015 19:23:56 PM] 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[23/2/2015 19:23:56 PM] 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[23/2/2015 19:23:56 PM] 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[23/2/2015 19:23:56 PM] 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[23/2/2015 19:23:56 PM] 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[23/2/2015 19:23:56 PM] 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
[23/2/2015 19:23:56 PM] 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
[23/2/2015 19:23:56 PM] 	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
[23/2/2015 19:23:56 PM] 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
[23/2/2015 19:23:56 PM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
[23/2/2015 19:23:56 PM] 	at net.minecraft.client.main.Main.main(SourceFile:148)
[23/2/2015 19:23:56 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23/2/2015 19:23:56 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23/2/2015 19:23:56 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23/2/2015 19:23:56 PM] 	at java.lang.reflect.Method.invoke(Unknown Source)
[23/2/2015 19:23:56 PM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[23/2/2015 19:23:56 PM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[23/2/2015 19:23:56 PM] Caused by: java.lang.ExceptionInInitializerError
[23/2/2015 19:23:56 PM] 	at java.lang.Class.forName0(Native Method)
[23/2/2015 19:23:56 PM] 	at java.lang.Class.forName(Unknown Source)
[23/2/2015 19:23:56 PM] 	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC6} [MFR Compat: Railcraft] (MINEFACTORYRELOADED-[1.7.10]2.8.0RC6-21.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
[23/2/2015 19:23:56 PM] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:359]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\**MINECRAFTUSERNAME**WolfWhisper\Desktop\ATLaucher\Instances\TheCrackPack\crash-reports\crash-2015-02-23_19.23.56-client.txt
[23/2/2015 19:23:56 PM] process has not exited
[23/2/2015 19:23:56 PM] java.lang.ProcessImpl.exitValue(Unknown Source)
[23/2/2015 19:23:56 PM] com.atlauncher.data.Instance$2.run(Instance.java:1150)
[23/2/2015 19:23:56 PM] Checking for updated files!
[23/2/2015 19:23:56 PM] No updates found!

**Comment by evknucklehead** [comment]
When the crash happens, open the launcher's console window and hit the Upload Log button. The launcher will do the upload and give you a link that you can give to us.

Unfortunately, the sections of the log that are most useful in this case are just inside the section you cut out.

**Comment by Sarloos** [comment]
Don't know how i missed that button ^^' ...Anyways here's the link:
http://paste.atlauncher.com/view/ce296d17

**Comment by skorfire1** [comment]
i have same problem

**Comment by evknucklehead** [comment]
Something is wrong with your copy of Factorization. You should be able to replace the one in the instance folder with another copy from the Launcher's Downloads folder. If that doesn't work, delete the copy in the downloads folder and reinstall the whole pack. Your worlds should be safe.

**Comment by Sarloos** [comment]
I've now tried what you proposed, but unfortunately it didn't seem to work :/ After that i tried removing all files and completely re-installed the launcher with everything. It didn't work either so i tried what you proposed again, still with no result. In case something has changed, here's the "new" log:
http://paste.atlauncher.com/view/b4bf49de

**Comment by evknucklehead** [comment]
No clue why Factorization isn't working for you. You can try pulling it and FZAddons (since it, naturally, relies on Factorization) and live without the stuff that it gives (most significantly the Barrels and the Lacerator, plus the lamps that light up a large area). That might let you get into the game, or it might expose more problems.

Another possibility is your RAM could be flaky. This isn't as likely as the exact location in Memory that Factorization is loading into shouldn't be the same every time you launch. Another possibility is to reinstall the launcher into a different location on your hard drive. Yet another remote possibility is to update your video drivers, though bad video drivers typically causes other types of errors than the one you're seeing, and would probably prevent the 1.6.4-based versions from running too.

Beyond those, I have no idea what might work to solve your issue.

**Comment by AXEarthquake** [comment]
I get the same problem http://paste.atlauncher.com/view/8d877185 (Is there any point fixing imgoing to get a new PC soon anyway?)

**Comment by evknucklehead** [comment]
@AXEarthquake  Your problem is not the same. Your problem is that you're running 32-bit java on a 64-bit OS. You need to install the 64-bit version of Java (preferably Java 7) in order to run the pack.

**Comment by AXEarthquake** [comment]
Ok could you give me a link for the correct one please?

**Comment by Sarloos** [comment]
You can download the 64-bit java at ATlauncher by following this link (click the first link in the "Download links" section);
http://www.atlauncher.com/help/32bit/

**Comment by Sarloos** [comment]
@evknucklehead When removing Factorization and FZAddons i actually get though to the menu. Unfortunately it now crashes when i try to create a new world. Reinstalling the launcher  into a different location yields the same result. My video drivers are fully updated. You can find the new log at;
http://paste.atlauncher.com/view/6d829a55

Thank you so much for the help up to now. I'm sorry to bother you with yet another problem :/

**Comment by evknucklehead** [comment]
Based on this latest log, double check that javaw.exe is not being blocked by your firewall. If it is not blocked, the last thing I can recommend is to completely uninstall and reinstall Java. 

Like I said, the video drivers was only a remote possibility. I didn't think it would be the case, but wanted to mention it due to the lack of any less-remote options at the time.
