### ISSUE TITLE
Server Crashes When Starting

### ISSUE THREAD

**Issue by Hpmason** [sciguyryan/TheCrackPack#847]
So I have my own home server for crackpack with plenty ram/memory, and I ran it a few times today trying to set up a world it worked perfectly. Now, after adding a world to the list of worlds, it no longer wants to run. It still provides a log and everything so here is one of the logs. Hope I someone out there can help.

LOG:

[13:30:15] [main/FATAL]: Failed to start the minecraft server
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 6598
	at com.google.gson.Gson.assertFullConsumption(Gson.java:779) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:769) ~[Gson.class:?]
	at net.minecraft.server.management.PlayerProfileCache.func_152657_b(SourceFile:156) ~[ns.class:?]
	at net.minecraft.server.management.PlayerProfileCache.<init>(SourceFile:42) ~[ns.class:?]
	at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:142) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.<init>(DedicatedServer.java:57) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1328) [MinecraftServer.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [forge-1.7.10-10.13.2.1277-universal.jar:?]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [forge-1.7.10-10.13.2.1277-universal.jar:?]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 6598
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1386) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:531) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:414) ~[JsonReader.class:?]
	at com.google.gson.Gson.assertFullConsumption(Gson.java:775) ~[Gson.class:?]
	... 18 more

**Comment by evknucklehead** [comment]
Whenever you see this in a crash report, it's almost always because of a corrupted usercache.json file. Deleting the file will fix the problem when it happens. 

The file is rebuilt as needed and is only used as a shortcut to looking up all the skin files for players who have either played on the server, or appeared as a mob or mob head because of the Headcrumbs mod.
