### ISSUE TITLE
Game closes when making item with tinkers construct

### ISSUE THREAD

**Issue by xflipflopx** [sciguyryan/TheCrackPack#859]
Hello! I recently learned of the ATLauncher and downloaded crack pack with my friends. I made a server and everything seemed fine until my younger brother decided to make a cross bow. His game closed, with atlauncer still there, it was just minecraft that crashed. I also attempted to make the crossbow for him and my game also froze then crashed with atlauncher still open. i notced this same problem with making short bows and long bows with tinkers construct.

I have the most recent Crackpack as well as all the mods downloaded including the ones checked off when you first downloaded crack pack (the optional ones EXCEPT the one unchecked Map mod, which i cannot remember the name). Please if you could help? is it a mod that conflicts? Thank you for reading

**Comment by xflipflopx** [comment]
Also heres what it said in my server log

[00:25:38] [Netty IO #0/ERROR] [FML/]: NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_40]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_40]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_40]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_40]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_40]
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:436) ~[UnpooledUnsafeDirectByteBuf.class:?]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:870) ~[AbstractByteBuf.class:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208) ~[NioSocketChannel.class:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:87) [AbstractNioByteChannel$NioByteUnsafe.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
[00:25:38] [Server thread/DEBUG] [NotEnoughItems/]: Unloading Player: xFlipflopx

**Comment by evknucklehead** [comment]
There is a known problem with making ranged weapons with certain materials in Tinkers' Construct. Specifically, any parts that are made from materials that are added by ExtraTiC. 

The safe materials are as follows:
* Steel
* Manyullyn
* Cobalt
* Alumite
* Ardite
* Pig Iron
* Iron
* Bronze
* Copper
* Thaumium
* Cactus
* Flint
* Obsidian
* Bone
* Netherrack
* Stone
* Green Slime (crystals)
* Blue Slime (crystals)
* Wood
* Paper

There are other materials that you can safely make the parts from, but they will not work in the Tool Station/Forge. Also, the valid shaft materials for arrows are now only Sticks, Bones, Sugar Canes, and Blaze Rods. 

You can still use the other materials for tools and melee weapons. Hopefully ExtraTiC will be updated soon so we can use them without crashing.

**Comment by xflipflopx** [comment]
Thank you for the swift response :D
