### ISSUE TITLE
Extreme Server Lag due to Anvil Chunk Loader Error

### ISSUE THREAD

**Issue by iRCinfinity** [sciguyryan/TheCrackPack#896]
This is a chunk of code from my console: 

25.03 11:00:15 [Server] WARN at java.lang.Thread.run(Thread.java:745)
25.03 11:00:15 [Server] WARN at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
25.03 11:00:15 [Server] WARN at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
25.03 11:00:15 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
25.03 11:00:15 [Server] WARN at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920)
25.03 11:00:15 [Server] WARN at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:254)
25.03 11:00:15 [Server] WARN at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:483)
25.03 11:00:15 [Server] WARN at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:338)
25.03 11:00:15 [Server] WARN at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:218)
25.03 11:00:15 [Server] WARN at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:388)
25.03 11:00:15 [Server] WARN at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
25.03 11:00:15 [Server] WARN at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
25.03 11:00:15 [Server] WARN java.util.ConcurrentModificationException
25.03 11:00:15 [Server] WARN at java.lang.Thread.run(Thread.java:745)
25.03 11:00:15 [Server] WARN at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
25.03 11:00:15 [Server] WARN at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
25.03 11:00:15 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
25.03 11:00:15 [Server] WARN at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920)
25.03 11:00:15 [Server] WARN at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:254)
25.03 11:00:15 [Server] WARN at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:483)
25.03 11:00:15 [Server] WARN at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:338)
25.03 11:00:15 [Server] WARN at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:218)
25.03 11:00:15 [Server] WARN at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:388)
25.03 11:00:15 [Server] WARN at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
25.03 11:00:15 [Server] WARN at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
25.03 11:00:15 [Server] WARN java.util.ConcurrentModificationException
25.03 11:00:15 [Server] WARN at java.lang.Thread.run(Thread.java:745)
25.03 11:00:15 [Server] WARN at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
25.03 11:00:15 [Server] WARN at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
25.03 11:00:15 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
25.03 11:00:15 [Server] WARN at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920)
25.03 11:00:15 [Server] WARN at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:254)
25.03 11:00:15 [Server] WARN at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:483)
25.03 11:00:15 [Server] WARN at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:338)
25.03 11:00:15 [Server] WARN at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:218)
25.03 11:00:15 [Server] WARN at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:388)
25.03 11:00:15 [Server] WARN at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
25.03 11:00:15 [Server] WARN at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
25.03 11:00:15 [Server] WARN java.util.ConcurrentModificationException
25.03 10:59:45 [Server] WARN at java.lang.Thread.run(Thread.java:745)
25.03 10:59:45 [Server] WARN at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
25.03 10:59:45 [Server] WARN at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
25.03 10:59:45 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
25.03 10:59:45 [Server] WARN at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920)
25.03 10:59:45 [Server] WARN at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:254)
25.03 10:59:45 [Server] WARN at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:483)
25.03 10:59:45 [Server] WARN at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:338)
25.03 10:59:45 [Server] WARN at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:218)
25.03 10:59:45 [Server] WARN at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:388)
25.03 10:59:45 [Server] WARN at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
25.03 10:59:45 [Server] WARN at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
25.03 10:59:45 [Server] WARN java.util.ConcurrentModificationException
25.03 10:59:45 [Server] WARN at java.lang.Thread.run(Thread.java:745)
25.03 10:59:45 [Server] WARN at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
25.03 10:59:45 [Server] WARN at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
25.03 10:59:45 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
25.03 10:59:45 [Server] WARN at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920)
25.03 10:59:45 [Server] WARN at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:254)
25.03 10:59:45 [Server] WARN at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:483)
25.03 10:59:45 [Server] WARN at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:338)
25.03 10:59:45 [Server] WARN at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:218)
25.03 10:59:45 [Server] WARN at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:388)
25.03 10:59:45 [Server] WARN at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
25.03 10:59:45 [Server] WARN at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)

--------------------------------

I apologize if there are spoiler tags that I don't know about, but it shouldn't be too big of an issue.

Anyways, my server lags sometimes and when it does this is the log from my console. At first I believed it to be chunk loaders, so I banned them all and deleted the forcedchunks file from my worlds. Didn't work. I don't know if there is possible one still in the world that just hasn't been moved or what but the problem has persisted since then.

I'm pretty new to servers, let alone mod packs, so if you could use simple language when explaining the possible issues with me I'd much appreciate it :/ This is the latest pack from the ATLauncher Crack Pack and it's running on 1.7.10 Cauldron Latest with Bukkit plugins.

I've not tested deleting all of the plugins, but if you think that may be the issue I will do it.

**Comment by evknucklehead** [comment]
AnvilChunkLoader is the function Minecraft uses to interpret the level's save files (the region.x.z.mca files for each dimension). 

The actual error is a Concurrent Modification Exception, which could be an indication of a conflict with the version of Java your server is running.

If you're running Java 8, consider downgrading to Java 7 Update 76. Certain tools used with Minecraft have issues running under Java 8. I haven't heard specifically that Cauldron is one of them, but if you're running an older build of Cauldron, it could certainly be experiencing this problem. Alternately, see if there's a newer build of Cauldron available that doesn't have problems with Java 8.

**Comment by iRCinfinity** [comment]
It took a lot of effort doing this through my host, but I was able to switch to Java 7. Sadly it didn't fix the issues.

The odd thing is that my current server migrated from an old save, and the old save works fine without the errors.

**Comment by evknucklehead** [comment]
When you say "old save", do you mean from an earlier version of the pack or from a single-player world in the current version of the pack?

There were some things changed between pack versions that may cause issues for people migrating, which is why I typically recommend a new world for people moving up to 2.0.3.0. As for transferring from single-player to a server, again, it's not recommended, though it usually doesn't cause many problems.

It is possible that one or more of the plugins is trying to access the files at the same time Minecraft is trying to modify them, which would also cause this error. Try removing plugins one at a time (IE remove one, see if the error still happens, if it does, put that one back and remove another one until you either don't get the error or you've tried all of them and still got the error) to see if you can narrow down what combinations may be causing the problem.

**Comment by iRCinfinity** [comment]
Okay I will do the plugin thing once I get off work, but to answer the rest; I originally had a 2 GB server with the saves on it (that worked fine) but I wanted to upgrade so I switched to an 8 GB after transferring the data (this is when the errors started, sometime after switching to this server) but I then switched to a 4 GB premium which is my current situation.

I still have the 2 GB server as well, but it hasn't been used in quite a while. I did a test earlier and it was working fine with or without Java 7. I'll update for the plugin thing later today or early tomorrow.

**Comment by iRCinfinity** [comment]
Removing the plugins didn't help, still giving me the errors. Could it be corrupted chunks or something?

**Comment by evknucklehead** [comment]
That certainly is possible. It will be tricky to nail down, though. I'd start with checking the chunks that players are in and working outward from them. See if there are any common patterns.

I wonder if anyone has made a chunk analyzer for modded Minecraft. That would certainly help in this situation...

**Comment by iRCinfinity** [comment]
Just from Googling it, it doesn't appear that way.

Hmm, I don't know. I suppose my last resort may simply be completely reloading the worlds. Which people aren't going to be happy about.
