### ISSUE TITLE
Crackpack server wont start

### ISSUE THREAD

**Issue by btaylor405080** [sciguyryan/TheCrackPack#915]
I have absolutely no clue why my server just randomly did this it seems to not want to start up now any help? It says 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[16:52:52] [Server thread/INFO]: Preparing spawn area: 91%
[16:52:52] [Server thread/ERROR]: Chunk file at 25,16 is in the wrong location;
relocating. (Expected 25, 16, got 27, 17)
[16:52:52] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ArrayIndexOutOfBoundsException: -12
        at net.minecraft.world.chunk.NibbleArray.func_76582_a(SourceFile:28) ~[a
pv.class:?]
        at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_76665_b(S
ourceFile:75) ~[apz.class:?]
        at net.minecraft.world.chunk.Chunk.func_76628_c(Chunk.java:548) ~[apx.cl
ass:?]
        at net.minecraft.world.chunk.Chunk.func_150812_a(Chunk.java:878) ~[apx.c
lass:?]
        at net.minecraft.world.chunk.Chunk.func_150813_a(Chunk.java:862) ~[apx.c
lass:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(Anvil
ChunkLoader.java:500) ~[aqk.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOP
rovider.java:41) ~[ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOP
rovider.java:12) ~[ChunkIOProvider.class:?]
        at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(Asynchr
onousExecutor.java:344) ~[AsynchronousExecutor.class:?]
        at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(Asyn
chronousExecutor.java:302) ~[AsynchronousExecutor.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(Chunk
IOExecutor.java:12) ~[ChunkIOExecutor.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderSe
rver.java:126) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProvide
rServer.java:101) ~[ms.class:?]
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.jav
a:265) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.jav
a:235) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(Dedicated
Server.java:258) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [M
inecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[li.class:?]
[16:52:52] [Server thread/ERROR]: This crash report has been saved to: C:\Users\
Ben\Desktop\ATL Server\.\crash-reports\crash-2015-04-02_16.52.52-server.txt
[16:52:52] [Server thread/INFO] [FML]: Applying holder lookups
[16:52:52] [Server thread/INFO] [FML]: Holder lookups applied
[16:52:52] [Server thread/INFO] [STDOUT]: [scala.Console$:println:148]: Stopped
[16:52:52] [pool-6-thread-1/INFO] [EnderIO]: ServerChannelRegister: Dimensional
Trasciever data saved to C:\Users\Ben\Desktop\ATL Server\.\world\enderio\dimensi
onalTransceiver.json
[16:52:52] [Server thread/INFO] [FML]: The state engine was in incorrect state S
ERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discar
ded.
Press any key to continue . . .

**Comment by evknucklehead** [comment]
Looks like that chunk has gotten corrupted somehow. You'll probably need to delete the chunk using either MCEdit or NBT Explorer. I would try deleting both listed chunks just to make sure.
