### ISSUE TITLE
Server wont let anyone use the mods

### ISSUE THREAD

**Issue by prattman** [sciguyryan/TheCrackPack#934]
Ive made a crack pack server and when anyone tried to place any block apart from vanilla blocks they just vanish, also i cant go to anything mod related. However i have no clue what is wrong.

**Comment by evknucklehead** [comment]
You need to use LaunchServer.bat or .sh depending on which OS you're running on. .bat is for Windows, .sh is for Linux and OS X. Just launching the minecraft.jar will launch a vanilla server without any mods, and the server will reject anything that isn't a vanilla block.

**Comment by NobleNik** [comment]
I have a close problem it is when i try to enter a server that i can enter with people online on it and it is green but i cant join it it says Timed Out please help crack pack 1.7.10

**Comment by evknucklehead** [comment]
First, make sure you have the same versions of the pack and any other mods the server is using.

Second, make sure the server isn't whitelisted. If it is, you'll need to contact the server admin to see if you can be added to the list.

If the server isn't whitelisted, it's possible the server is set with too many slots for its upstream bandwidth. This is something the server owner has to make sure of when they start the server, but not everyone realizes this. There are tools online to help server operators figure out about how many players their upstream rate can handle.

**Comment by NobleNik** [comment]
thank you

**Comment by Firespin44** [comment]
I am having this issue, and when i tried using the batch file it won't open the server. To have the server running i need to have the minecraft server.jar open. Please help i am very frustrated because i have tried everything.

**Comment by evknucklehead** [comment]
@Firespin44 The batch file is set up to load the forge .jar file, which in turn opens the minecraft server.jar. Post a copy of what it says when you run the batch file so we can figure out why it's not working.

**Comment by Firespin44** [comment]
This is the copy of the batch file



        MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC6} [MFR Compat: BackTo
ols] (MINEFACTORYRELOADED-[1.7.10]2.8.0RC6-21.jar) Unloaded->Constructed->Pre-in
itialized->Initialized->Post-initialized
        MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC6} [MFR Compat: Build
Craft] (MINEFACTORYRELOADED-[1.7.10]2.8.0RC6-21.jar) Unloaded->Constructed->Pre-
initialized->Initialized->Post-initialized
        MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC6} [MFR Compat: Choco
craft] (MINEFACTORYRELOADED-[1.7.10]2.8.0RC6-21.jar) Unloaded->Constructed->Pre-
initialized->Initialized->Post-initialized
        MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC6} [MFR Compat: Extr
aBiomes] (MINEFACTORYRELOADED-[1.7.10]2.8.0RC6-21.jar) Unloaded->Constructed->Pr
e-initialized->Initialized->Post-initialized
        MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC6} [MFR Compat: Forestr
y] (MINEFACTORYRELOADED-[1.7.10]2.8.0RC6-21.jar) Unloaded->Constructed->Pre-init
ialized->Initialized->Post-initialized
        MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC6} [MFR Compat:
ForgeMicroblock] (MINEFACTORYRELOADED-[1.7.10]2.8.0RC6-21.jar) Unloaded->Constru
cted->Pre-initialized->Initialized->Post-initialized
        MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC6} [MFR Compat: IC2] (MINEFA
CTORYRELOADED-[1.7.10]2.8.0RC6-21.jar) Unloaded->Constructed->Pre-initialized->I
nitialized->Post-initialized
        MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC6} [MFR Compat: Mystcr
aft] (MINEFACTORYRELOADED-[1.7.10]2.8.0RC6-21.jar) Unloaded->Constructed->Pre-in
itialized->Initialized->Post-initialized
        ProjRed|Exploration{4.5.7.58} [ProjectRed-Exploration] (PROJECTRED-WORLD
-1.7.10-4.5.7.58.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-
initialized
        MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC6} [MFR Compat ProjectRe
d] (MINEFACTORYRELOADED-[1.7.10]2.8.0RC6-21.jar) Unloaded->Constructed->Pre-init
ialized->Initialized->Post-initialized
        MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC6} [MFR Compat: Railcr
aft] (MINEFACTORYRELOADED-[1.7.10]2.8.0RC6-21.jar) Unloaded->Constructed->Pre-in
itialized->Initialized->Post-initialized
        MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC6} [MFR Compat: RP2] (MINEFA
CTORYRELOADED-[1.7.10]2.8.0RC6-21.jar) Unloaded->Constructed->Pre-initialized->I
nitialized->Post-initialized
        MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC6} [MFR Compat:
 Sufficient Biomes] (MINEFACTORYRELOADED-[1.7.10]2.8.0RC6-21.jar) Unloaded->Cons
tructed->Pre-initialized->Initialized->Post-initialized
        MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC6} [MFR Compat: Thaum
craft] (MINEFACTORYRELOADED-[1.7.10]2.8.0RC6-21.jar) Unloaded->Constructed->Pre-
initialized->Initialized->Post-initialized
        MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC6} [MFR Compat:
 Thermal Expansion] (MINEFACTORYRELOADED-[1.7.10]2.8.0RC6-21.jar) Unloaded->Cons
tructed->Pre-initialized->Initialized->Post-initialized
        MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0RC6} [MFR Compat: Tinke
rs' Construct] (MINEFACTORYRELOADED-[1.7.10]2.8.0RC6-21.jar) Unloaded->Construct
ed->Pre-initialized->Initialized->Post-initialized
        TwilightForest{2.3.2} [The Twilight Forest] (TWILIGHTFOREST-1.7.10-2.3.2
.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC6} [MFR Compat: T
wilightForest] (MINEFACTORYRELOADED-[1.7.10]2.8.0RC6-21.jar) Unloaded->Construct
ed->Pre-initialized->Initialized->Post-initialized
        MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC6} [MFR Compat: Vanilla]
 (MINEFACTORYRELOADED-[1.7.10]2.8.0RC6-21.jar) Unloaded->Constructed->Pre-initia
lized->Initialized->Post-initialized
        MineMenu{1.2.0} [MineMenu] (MINEMENU-1.7.10-1.2.0.B44-UNIVERSAL.jar) Unl
oaded->Constructed->Pre-initialized->Initialized->Post-initialized
        MineTweaker3{3.0.9B} [MineTweaker 3] (MINETWEAKER3-1.7.10-3.0.9C.jar) Un
loaded->Constructed->Pre-initialized->Initialized->Post-initialized
        ModTweaker{0.6} [ModTweaker] (MODTWEAKER-1.7.X-0.6-22.jar) Unloaded->Con
structed->Pre-initialized->Initialized->Post-initialized
        Morph{0.9.1} [Morph] (MORPH-BETA-0.9.1.jar) Unloaded->Constructed->Pre-i
nitialized->Initialized->Post-initialized
        Morpheus{1.7.10-1.5.26} [Morpheus] (MORPHEUS-1.7.10-1.5.26.jar) Unloaded
->Constructed->Pre-initialized->Initialized->Post-initialized
        NEIAddons{1.12.3.11} [NEI Addons] (NEIADDONS-MC1710-1.12.3.11.jar) Unloa
ded->Constructed->Pre-initialized->Initialized->Post-initialized
        NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany] (NEIADDONS-MC1710-1.12.
3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry] (NEIADDONS-MC1710-1
.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initiali
zed
        NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables] (NEIAD
DONS-MC1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->
Post-initialized
        NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo] (NEIADDONS-MC1710-
1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initial
ized
        neiintegration{1.0.3} [NEI Integration] (NEIINTEGRATION-MC1.7.10-1.0.3.j
ar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        NetherOres{1.7.10R2.3.0RC4} [Nether Ores] (NETHERORES-[1.7.10]2.3.0RC4-8
.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        recipehandler{0.2} [NoMoreRecipeConflict] (NOMORERECIPECONFLICT-0.2(1.7.
10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        OpenMods{0.6} [OpenMods] (OPENMODSLIB-1.7.10-0.6.jar) Unloaded->Construc
ted->Pre-initialized->Initialized->Post-initialized
        OpenBlocks{1.3} [OpenBlocks] (OPENBLOCKS-1.7.10-1.3.jar) Unloaded->Const
ructed->Pre-initialized->Initialized->Post-initialized
        harvestcraft{1.7.10d} [Pam's HarvestCraft] (PAMS HARVESTCRAFT 1.7.10F.ja
r) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        PneumaticCraft{1.5.1-49} [PneumaticCraft] (PNEUMATICCRAFT-1.7.10-1.5.1-4
9-UNIVERSAL.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initi
alized
        JotatosPracticalities{0.5.0} [Practicalities] (PRACTICALITIES-1.7.10-0.5
.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        pressure{1.0.1.48} [Pressure Pipes] (PRESSURE-MC1710-1.0.1.48.jar) Unloa
ded->Constructed->Pre-initialized->Initialized->Post-initialized
        ProjRed|Compatibility{4.5.7.58} [ProjectRed-Compatibility] (PROJECTRED-C
OMPAT-1.7.10-4.5.7.58.jar) Unloaded->Constructed->Pre-initialized->Initialized->
Post-initialized
        ProjRed|Integration{4.5.7.58} [ProjectRed-Integration] (PROJECTRED-INTEG
RATION-1.7.10-4.5.7.58.jar) Unloaded->Constructed->Pre-initialized->Initialized-
>Post-initialized
        ProjRed|Illumination{4.5.7.58} [ProjectRed-Illumination] (PROJECTRED-LIG
HTING-1.7.10-4.5.7.58.jar) Unloaded->Constructed->Pre-initialized->Initialized->
Post-initialized
        RandomThings{2.2.3} [Random Things] (RANDOMTHINGS-2.2.3.jar) Unloaded->C
onstructed->Pre-initialized->Initialized->Post-initialized
        RedstoneArsenal{1.7.10R1.1.0RC1} [Redstone Arsenal] (REDSTONEARSENAL-[1.
7.10]1.1.0RC1-23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-
initialized
        RedstonePasteMod{1.6.2} [Redstone Paste] (REDSTONEPASTEMOD-1.7.10-1.6.2.
jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        RefinedRelocation{1.0.7d} [Refined Relocation] (REFINEDRELOCATION-1.7.10
-1.0.7D.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initializ
ed
        Roguelike{1.3.5} [Roguelike Dungeons] (ROGUELIKE-1.7.10-1.3.5.jar) Unloa
ded->Constructed->Pre-initialized->Initialized->Post-initialized
        Sanguimancy{1.1.8} [Sanguimancy] (SANGUIMANCY-1.7.10-1.1.8-4.jar) Unload
ed->Constructed->Pre-initialized->Initialized->Post-initialized
        simplyjetpacks{1.3.2} [Simply Jetpacks] (SIMPLYJETPACKS-MC1.7.10-1.3.2.j
ar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        SolarFlux{1.7.10-0.5} [Solar Flux] (SOLARFLUX-1.7.10-0.5.jar) Unloaded->
Constructed->Pre-initialized->Initialized->Post-initialized
        SpecialMobs{3.0.3} [Special Mobs] (SPECIALMOBS-1.7.10-3.0.3.jar) Unloade
d->Constructed->Pre-initialized->Initialized->Post-initialized
        Stackie{1.5.1.30} [Stackie] (STACKIE-1.7.10-1.5.1.30-UNIVERSAL.jar) Unlo
aded->Constructed->Pre-initialized->Initialized->Post-initialized
        StevesCarts{2.0.0.b18} [Steve's Carts 2] (STEVESCARTS2.0.0.B18.jar) Unlo
aded->Constructed->Pre-initialized->Initialized->Post-initialized
        StevesFactoryManager{A93} [Steve's Factory Manager] (STEVESFACTORYMANAGE
RA93.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        StevesWorkshop{0.5.1} [Steve's Workshop] (STEVESWORKSHOP-0.5.1.jar) Unlo
aded->Constructed->Pre-initialized->Initialized->Post-initialized
        supercraftingframe{1.7.10.1} [Super Crafting Frame] (SUPERCRAFTINGFRAME-
1.7.10.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initiali
zed
        ThaumicExploration{0.6.0} [Thaumic Exploration] (THAUMICEXPLORATION-1.7.
10-1.1-34.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initial
ized
        TMechworks{1.7.10-86.e500b88} [Tinkers' Mechworks] (TMECHWORKS-1.7.10-0.
2.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        TooMuchRain{%VERSION%} [TooMuchRain] (TOOMUCHRAIN-1.7.2-1.0.0-B5-UNIVERS
AL.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        TSteelworks{1.7.10-1.0.6} [Tinkers' Steelworks] (TSTEELWORKS-1.7.10-1.0.
6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        VeinMiner{0.26.0_build.unknown} [Vein Miner] (VeinMiner-1.7.10_0.26.1.un
known.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized

        VeinMinerModSupport{0.26.0_build.unknown} [Mod Support] (VeinMiner-1.7.1
0_0.26.1.unknown.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-
initialized
        wawla{1.1.0} [What Are We Looking At] (WAWLA-1.1.0_1.7.10.jar) Unloaded-
>Constructed->Pre-initialized->Initialized->Post-initialized
        weaponmod{v1.14.3} [Balkon's WeaponMod] (WEAPONMOD-1.14.3.jar) Unloaded-
>Constructed->Pre-initialized->Initialized->Post-initialized
        witchery{0.21.2} [Witchery] (WITCHERY-1.7.10-0.21.2.jar) Unloaded->Const
ructed->Pre-initialized->Initialized->Post-initialized
        WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-UNIVERSAL.jar)
 Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-UNIVERSAL.
jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-UNIVERSAL.ja
r) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        Ztones{1.7.10} [Ztones] (ZTONES-1.7.10-2.2.jar) Unloaded->Constructed->P
re-initialized->Initialized->Post-initialized
        McMultipart{1.1.1.320} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.
10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized-
>Post-initialized
        aobd{2.3.5} [Another One Bites The Dust] (AOBD-2.3.5.jar) Unloaded->Cons
tructed->Pre-initialized->Initialized->Post-initialized
        denseores{1.0} [Dense Ores] (DENSEORES-1.5.jar) Unloaded->Constructed->P
re-initialized->Initialized->Post-initialized
        ForgeMicroblock{1.1.1.320} [Forge Microblocks] (ForgeMultipart-1.7.10-1.
1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post
-initialized
        asielibcore{} [AsieLib CoreMod] (minecraft.jar) Unloaded->Disabled
[12:45:38] [Server thread/ERROR] [FML]: The following problems were captured dur
ing this phase
[12:45:38] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalArgumentException: java.lang.NoClassDefFoundError: net/minecraf
t/client/renderer/GLAllocation
        at factorization.coremod.AtVerifier.verify(AtVerifier.java:55) ~[FACTORI
ZATION-1.7.10-0.8.88.7.jar:?]
        at factorization.shared.Core.validateEnvironment(Core.java:576) ~[Core.c
lass:?]
        at factorization.shared.Core.modsLoaded(Core.java:188) ~[Core.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0
_79]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0
_79]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.7.0_79]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_79]
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContain
er.java:513) ~[FMLModContainer.class:?]
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.7.0_79]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_79]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscribe
r.java:74) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(Sy
nchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[min
ecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.jav
a:304) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecra
ft_server.1.7.10.jar:?]
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadContro
ller.java:208) ~[LoadController.class:?]
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadControll
er.java:187) ~[LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0
_79]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0
_79]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.7.0_79]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_79]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscribe
r.java:74) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(Sy
nchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[min
ecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.jav
a:304) ~[minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecra
ft_server.1.7.10.jar:?]
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadControl
ler.java:118) ~[LoadController.class:?]
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694) ~[Loader.c
lass:?]
        at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHan
dler.java:97) ~[FMLServerHandler.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler
.java:319) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(Dedicated
Server.java:210) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [M
inecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[li.class:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/GLAlloc
ation
        at net.minecraft.client.renderer.Tessellator.<init>(Tessellator.java:142
) ~[bmh.class:?]
        at net.minecraft.client.renderer.Tessellator.<clinit>(Tessellator.java:1
05) ~[bmh.class:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.7.0_79]
        at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_79]
        at factorization.coremod.AtVerifier.validate(AtVerifier.java:66) ~[FACTO
RIZATION-1.7.10-0.8.88.7.jar:?]
        at factorization.coremod.AtVerifier.verify(AtVerifier.java:53) ~[FACTORI
ZATION-1.7.10-0.8.88.7.jar:?]
        ... 33 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.GLAll
ocation
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLo
ader.java:191) ~[launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
        at net.minecraft.client.renderer.Tessellator.<init>(Tessellator.java:142
) ~[bmh.class:?]
        at net.minecraft.client.renderer.Tessellator.<clinit>(Tessellator.java:1
05) ~[bmh.class:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.7.0_79]
        at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_79]
        at factorization.coremod.AtVerifier.validate(AtVerifier.java:66) ~[FACTO
RIZATION-1.7.10-0.8.88.7.jar:?]
        at factorization.coremod.AtVerifier.verify(AtVerifier.java:53) ~[FACTORI
ZATION-1.7.10-0.8.88.7.jar:?]
        ... 33 more
Caused by: java.lang.NullPointerException
[12:45:38] [Server thread/WARN] [FML]: Can't revert to frozen GameData state wit
hout freezing first.
[12:45:38] [Server thread/INFO] [FML]: Applying holder lookups
[12:45:38] [Server thread/WARN] [FML]: Unable to lookup CompactMachines:interfac
eblock for public static org.dave.CompactMachines.block.BlockCM org.dave.Compact
Machines.init.ModBlocks.interfaceblock. Is there something wrong with the regist
ry?
[12:45:38] [Server thread/INFO] [FML]: Holder lookups applied
[12:45:38] [Server thread/INFO] [STDOUT]: [scala.Console$:println:148]: Stopped
[12:45:38] [Server thread/WARN] [EnderIO]: Failed to write Transciever Channels
on exit: java.util.concurrent.ExecutionException: java.lang.NullPointerException

[12:45:38] [Server thread/ERROR] [factorization.misc]: Skipping event FMLServerS
toppedEvent and marking errored mod factorization.misc since required dependency
 factorization has errored
[12:45:38] [Server thread/ERROR] [FZAddons]: Skipping event FMLServerStoppedEven
t and marking errored mod FZAddons since required dependency factorization has e
rrored
[12:45:38] [Server thread/INFO] [FML]: The state engine was in incorrect state E
RRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[12:45:38] [Server thread/INFO] [FML]: The state engine was in incorrect state E
RRORED and forced into state AVAILABLE. Errors may have been discarded.
Press any key to continue . . .

**Comment by evknucklehead** [comment]
Hmm. Looks like an OpenGL error occurred with Factorization. Make sure the server's graphics drivers are up to date from the chip maker's (Intel/AMD/Nvidia) website. 

Also, while I don't know of any specific problems with Veinminer, it's not part of the default pack, so no guarantees that it's not causing problems.

**Comment by Firespin44** [comment]
So I have an AMD graphics card so I should go to the AMD website and try to update the graphics card software?

**Comment by Firespin44** [comment]
Is there a youtube video you could link so I could see how to do it, because i just got this computer and i am new to the pc master race, and i don't want to mess anything up.

**Comment by evknucklehead** [comment]
Go to AMD's website, hover over "Drivers + Support", then select "Drivers + Download Center". This will bring you to the download center page. The easiest way from here is to select the Auto Detect option and follow the instructions it provides.

**Comment by Firespin44** [comment]
This Auto Detect update thing is free right?

**Comment by Firespin44** [comment]
I updated my AMD drivers but it still won't work......I don't know if this matters but the only way i can connect to the server is to have the mincraft_server 1.7.10 jar file open.
