### ISSUE TITLE
CrackPack 1.5.1 starts to load for 5 seconds and then brings me back to the home screen of the atluancher

### ISSUE THREAD

**Issue by kingawesome3579** [sciguyryan/TheCrackPack#978]
I need help heres my log:
[10/5/2015 20:39:29 PM] Loading Language: English
[10/5/2015 20:39:29 PM] Loading Language: English
[10/5/2015 20:39:29 PM] ATLauncher Version: 3.2.2.6
[10/5/2015 20:39:29 PM] Operating System: Windows 8.1
[10/5/2015 20:39:29 PM] RAM Available: 8127MB
[10/5/2015 20:39:29 PM] Java Version: Launcher: 1.8.0_45, Minecraft: 1.8.0_45
[10/5/2015 20:39:29 PM] Java Path: C:\Program Files\Java\jre1.8.0_45
[10/5/2015 20:39:29 PM] 64 Bit Java: true
[10/5/2015 20:39:29 PM] Launcher Directory: **USERSDIR**
[10/5/2015 20:39:29 PM] Using Theme: Default Theme by RyanTheAllmighty
[10/5/2015 20:39:29 PM] Showing splash screen and loading everything
[10/5/2015 20:39:29 PM] Checking for updated files!
[10/5/2015 20:39:29 PM] No updates found!
[10/5/2015 20:39:30 PM] Loading external library authlib-1.5.17.jar to classpath
[10/5/2015 20:39:30 PM] Loading external library log4j-api-2.0-beta9.jar to classpath
[10/5/2015 20:39:30 PM] Loading external library log4j-core-2.0-beta9.jar to classpath
[10/5/2015 20:39:30 PM] Loading external library guava-17.0.jar to classpath
[10/5/2015 20:39:30 PM] Loading external library commons-io-2.4.jar to classpath
[10/5/2015 20:39:30 PM] Loading external library commons-lang3-3.3.2.jar to classpath
[10/5/2015 20:39:30 PM] [Background] Checking Minecraft Versions Started
[10/5/2015 20:39:30 PM] Checking account UUID's!
[10/5/2015 20:39:30 PM] Launcher finished loading everything
[10/5/2015 20:39:30 PM] Launcher opening
[10/5/2015 20:39:30 PM] Made By Bob*
[10/5/2015 20:39:30 PM] *(Not Actually)
[10/5/2015 20:39:30 PM] Setting up Bottom Bar
[10/5/2015 20:39:30 PM] Finished Setting up Bottom Bar
[10/5/2015 20:39:30 PM] Setting up Tabs
[10/5/2015 20:39:31 PM] Finished Setting up Tabs
[10/5/2015 20:39:31 PM] Showing Launcher
[10/5/2015 20:39:32 PM] [Background] Checking Minecraft Versions Complete
[10/5/2015 20:39:37 PM] Logging into Minecraft!
[10/5/2015 20:39:37 PM] Trying to login with access token!
[10/5/2015 20:39:38 PM] Launching pack The Crack Pack 1.5.1.0-TCP for Minecraft 1.6.4
[10/5/2015 20:39:38 PM] Launching Minecraft with the following arguments (user related stuff has been removed): [C:\Program Files\Java\jre1.8.0_45\bin\javaw, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -XX:-OmitStackTraceInFastThrow, -XX:+UseConcMarkSweepGC, -XX:+CMSIncrementalMode, -XX:-UseAdaptiveSizePolicy, -Xms256M, -Xmx4096M, -XX:MetaspaceSize=256M, -Duser.language=en, -Duser.country=US, -Dfml.log.level=INFO, -Djava.library.path=**USERSDIR**\Instances\hope\bin\natives, -cp, **USERSDIR**\ATLauncher.exe;anything;**USERSDIR**\Instances\hope\jarmods\forge-1.6.4-9.11.1.965-universal.jar;**USERSDIR**\Instances\hope\bin\launchwrapper-1.8.jar;**USERSDIR**\Instances\hope\bin\asm-all-4.1.jar;**USERSDIR**\Instances\hope\bin\scala-library-2.10.2.jar;**USERSDIR**\Instances\hope\bin\scala-compiler-2.10.2.jar;**USERSDIR**\Instances\hope\bin\lzma-0.0.1.jar;**USERSDIR**\Instances\hope\bin\jopt-simple-4.5.jar;**USERSDIR**\Instances\hope\bin\codecjorbis-20101023.jar;**USERSDIR**\Instances\hope\bin\codecwav-20101023.jar;**USERSDIR**\Instances\hope\bin\libraryjavasound-20101123.jar;**USERSDIR**\Instances\hope\bin\librarylwjglopenal-20100824.jar;**USERSDIR**\Instances\hope\bin\soundsystem-20120107.jar;**USERSDIR**\Instances\hope\bin\argo-2.25_fixed.jar;**USERSDIR**\Instances\hope\bin\bcprov-jdk15on-1.47.jar;**USERSDIR**\Instances\hope\bin\guava-14.0.jar;**USERSDIR**\Instances\hope\bin\commons-lang3-3.1.jar;**USERSDIR**\Instances\hope\bin\commons-io-2.4.jar;**USERSDIR**\Instances\hope\bin\jinput-2.0.5.jar;**USERSDIR**\Instances\hope\bin\jutils-1.0.0.jar;**USERSDIR**\Instances\hope\bin\gson-2.2.2.jar;**USERSDIR**\Instances\hope\bin\lwjgl-2.9.0.jar;**USERSDIR**\Instances\hope\bin\lwjgl_util-2.9.0.jar;**USERSDIR**\Instances\hope\bin\minecraft.jar, net.minecraft.launchwrapper.Launch, --username, REDACTED, --session, token:REDACTED:afc7b0300a7e44839a555ede584b874f, --version, 1.6.4, --gameDir, **USERSDIR**\Instances\hope, --assetsDir, **USERSDIR**\Configs\Resources\virtual\legacy, --width=854, --height=480, --tweakClass=cpw.mods.fml.common.launcher.FMLTweaker]
[10/5/2015 20:39:38 PM] May 10, 2015 8:39:38 PM net.minecraft.launchwrapper.LogWrapper log
[10/5/2015 20:39:38 PM] INFO: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[10/5/2015 20:39:38 PM] May 10, 2015 8:39:38 PM net.minecraft.launchwrapper.LogWrapper log
[10/5/2015 20:39:38 PM] INFO: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[10/5/2015 20:39:38 PM] May 10, 2015 8:39:38 PM net.minecraft.launchwrapper.LogWrapper log
[10/5/2015 20:39:38 PM] INFO: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[10/5/2015 20:39:38 PM] [INFO] [ForgeModLoader] Forge Mod Loader version 6.4.49.965 for Minecraft 1.6.4 loading
[10/5/2015 20:39:38 PM] [INFO] [ForgeModLoader] Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_45, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jre1.8.0_45
[10/5/2015 20:39:38 PM] [WARNING] [ForgeModLoader] The coremod net.minecraftforge.lex.sortfix.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10/5/2015 20:39:38 PM] [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10/5/2015 20:39:38 PM] [WARNING] [ForgeModLoader] The coremod worldcore.asm.WCFMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10/5/2015 20:39:38 PM] [WARNING] [ForgeModLoader] The coremod appeng.transformer.AppEngCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10/5/2015 20:39:38 PM] [INFO] [ForgeModLoader] [AppEng] Core Init
[10/5/2015 20:39:38 PM] [WARNING] [ForgeModLoader] The coremod biomesoplenty.asm.BOPFMLLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10/5/2015 20:39:38 PM] [INFO] [STDERR] Warning: version of ForgeMultipart-universal-1.6.4-, 1.0.0.250 is newer than request 1.0.0.244
[10/5/2015 20:39:38 PM] [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10/5/2015 20:39:38 PM] [WARNING] [ForgeModLoader] The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10/5/2015 20:39:38 PM] [WARNING] [ForgeModLoader] The coremod mcp.mobius.evoc.asm.CoreDescription does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10/5/2015 20:39:38 PM] [WARNING] [ForgeModLoader] The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10/5/2015 20:39:38 PM] [WARNING] [ForgeModLoader] The coremod mekanism.common.asm.LoadingHook does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10/5/2015 20:39:38 PM] [WARNING] [ForgeModLoader] The coremod mcp.mobius.mobiuscore.asm.CoreDescription does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10/5/2015 20:39:38 PM] [WARNING] [ForgeModLoader] The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10/5/2015 20:39:38 PM] [WARNING] [ForgeModLoader] The coremod openblocks.OpenBlocksCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10/5/2015 20:39:39 PM] [WARNING] [ForgeModLoader] The coremod openeye.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10/5/2015 20:39:39 PM] [WARNING] [ForgeModLoader] The coremod openmods.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10/5/2015 20:39:39 PM] [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10/5/2015 20:39:39 PM] [WARNING] [ForgeModLoader] The coremod resonant.core.ResonantPluginLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10/5/2015 20:39:39 PM] [WARNING] [ForgeModLoader] The coremod tconstruct.preloader.TConstructLoaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10/5/2015 20:39:39 PM] [INFO] [TCon-Preloader] Scalpel. Suction. Lumber axe. CLEAR! *zap*
[10/5/2015 20:39:39 PM] [INFO] [TCon-Preloader] Constructing preloader (Modules: [tconstruct.preloader.AccessTransformers, tconstruct.preloader.ASMInterfaceRepair])
[10/5/2015 20:39:39 PM] [INFO] [TCon-Preloader] Found a properties file. Attempting load...
[10/5/2015 20:39:39 PM] [INFO] [TCon-Preloader] Loaded properties successfully. Using specified settings.
[10/5/2015 20:39:39 PM] [WARNING] [ForgeModLoader] The coremod universalelectricity.core.UELoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10/5/2015 20:39:39 PM] [WARNING] [ForgeModLoader] The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[10/5/2015 20:39:39 PM] [INFO] [ForgeModLoader] Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[10/5/2015 20:39:39 PM] [INFO] [ForgeModLoader] Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[10/5/2015 20:39:39 PM] [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[10/5/2015 20:39:39 PM] [SEVERE] [ForgeModLoader] Unable to launch
[10/5/2015 20:39:39 PM] java.util.ConcurrentModificationException
[10/5/2015 20:39:39 PM] 	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
[10/5/2015 20:39:39 PM] 	at java.util.ArrayList$Itr.remove(Unknown Source)
[10/5/2015 20:39:39 PM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
[10/5/2015 20:39:39 PM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
[10/5/2015 20:39:40 PM] Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[10/5/2015 20:39:40 PM] Checking for updated files!
[10/5/2015 20:39:40 PM] No updates found!

**Comment by kingawesome3579** [comment]
Please help I really want to play 1.5.1

**Comment by evknucklehead** [comment]
Minecraft Forge for 1.6.4 has a bug that causes this error when run under most versions of Java 8. There is a fix available here: https://forums.atlauncher.com/thread-4767.html

Also, this isn't a professional help service. It's practically a miracle that I happened to see your post as quickly as I did. It usually takes hours or even days sometimes for someone to respond because we're all volunteers who happen to have some troubleshooting experience and a desire to help our fellow MindCrack fans. So, please, be patient in the future.

**Comment by kingawesome3579** [comment]
I know i was just saying how much i wanted to play i expented it to be a couple of days but thanks for helping

**Comment by kingawesome3579** [comment]
K i didn't realize that i am sorry
