### ISSUE TITLE
Server crashes when I attempt to join

### ISSUE THREAD

**Issue by Steveloco1** [sciguyryan/TheCrackPack#989]
Everytime I attempt to join the server, I end up crashing. I do not know why and it happened suddenly so I was wondering if you can tell me what is the cause of my crashing server and how I may possibly fix it. 

[EDIT: After reading the crash report (correct me if im wrong, my horse (Cinna-MON) is crashing my server for a reason I do not know....how can I kill or remove him from the world since I cannot go into the server and kill him manually with a sword.]

This was my server crash report:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 5/23/15 9:49 PM
Description: Ticking entity

java.lang.ClassCastException: jds.bibliocraft.tileentities.TileEntityPotionShelf cannot be cast to jds.bibliocraft.tileentities.TileEntityBookcase
	at jds.bibliocraft.blocks.BlockBookcase.func_149719_a(BlockBookcase.java:323)
	at jds.bibliocraft.blocks.BlockBookcase.func_149743_a(BlockBookcase.java:359)
	at net.minecraft.world.World.func_72945_a(World.java:1437)
	at cofh.asm.HooksCore.getEntityCollisonBoxes(HooksCore.java:96)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:596)
	at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1490)
	at net.minecraft.entity.passive.EntityHorse.func_70612_e(EntityHorse.java:1265)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1814)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
	at net.minecraft.entity.EntityAgeable.func_70636_d(SourceFile:95)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:37)
	at net.minecraft.entity.passive.EntityHorse.func_70636_d(EntityHorse.java:966)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at net.minecraft.entity.passive.EntityHorse.func_70071_h_(EntityHorse.java:1001)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at jds.bibliocraft.blocks.BlockBookcase.func_149719_a(BlockBookcase.java:323)
	at jds.bibliocraft.blocks.BlockBookcase.func_149743_a(BlockBookcase.java:359)
	at net.minecraft.world.World.func_72945_a(World.java:1437)
	at cofh.asm.HooksCore.getEntityCollisonBoxes(HooksCore.java:96)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:596)
	at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1490)
	at net.minecraft.entity.passive.EntityHorse.func_70612_e(EntityHorse.java:1265)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1814)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
	at net.minecraft.entity.EntityAgeable.func_70636_d(SourceFile:95)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:37)
	at net.minecraft.entity.passive.EntityHorse.func_70636_d(EntityHorse.java:966)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
	at net.minecraft.entity.passive.EntityHorse.func_70071_h_(EntityHorse.java:1001)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: EntityHorse (net.minecraft.entity.passive.EntityHorse)
	Entity ID: 1137
	Entity Name: Cinna-MON
	Entity's Exact location: -247.30, 63.00, 2370.20
	Entity's Block location: World: (-248,63,2370), Chunk: (at 8,3,2 in -16,148; contains blocks -256,0,2368 to -241,255,2383), Region: (-1,4; contains chunks -32,128 to -1,159, blocks -512,0,2048 to -1,255,2559)
	Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [GCEntityPlayerMP['Steveloco1'/624, l='world', x=-235.16, y=54.02, z=2353.94]]
	Chunk stats: ServerChunkCache: 698 Drop: 0
	Level seed: 8134392451922062662
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (480,64,1521), Chunk: (at 0,4,1 in 30,95; contains blocks 480,0,1520 to 495,255,1535), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
	Level time: 19081440 game time, 19744753 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 30849 (now: false), thunder time: 104843 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by evknucklehead** [comment]
It looks like your horse is triggering a bug with the hitboxes in Bibliocraft. Were you or your horse next to a potion shelf when the crash started happening?

It's possible you may be able to move the horse with either MCEdit or NBT Explorer so it's not next to the shelf in question. If that doesn't work, the same programs can be used to delete the horse as well.
